#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export MSP_EXAMPLE_CPYTHON_DISPLAY_NAME="MSPPlaygroundApp"
export MSP_EXAMPLE_CPYTHON_XCFRAMEWORK_PATH="${MSP_PLAYGROUND_PYTHON_XCFRAMEWORK_PATH:-}"
export MSP_EXAMPLE_CPYTHON_PATH_HINT="MSP_PLAYGROUND_PYTHON_XCFRAMEWORK_PATH"
export MSP_EXAMPLE_REQUIRE_CPYTHON="${MSP_PLAYGROUND_REQUIRE_CPYTHON:-}"
export MSP_EXAMPLE_REQUIRE_CPYTHON_DISABLE_HINT="MSP_PLAYGROUND_REQUIRE_CPYTHON=0"

exec bash "$script_dir/../../../Shared/Python/embed-cpython-runtime.sh"
