import Foundation
import XCTest

final class ModelShellProxyReleaseGateVerifierSourceGuardTests: XCTestCase {
    func testFinalGateVerifierRequiresEveryReleaseEvidenceClass() throws {
        let rootURL = try ModelShellProxyConformanceSupport.packageRoot()
        let scriptsURL = rootURL
            .appendingPathComponent("Conformance")
            .appendingPathComponent("Scripts")
        let finalGateVerifierSupportURL = scriptsURL
            .appendingPathComponent("final_gate_verifier_support")
        let finalGateVerifier = try [
            scriptsURL.appendingPathComponent("verify_final_exec_session_release_gate_report.py"),
            finalGateVerifierSupportURL.appendingPathComponent("__init__.py"),
            finalGateVerifierSupportURL.appendingPathComponent("contract.py"),
            finalGateVerifierSupportURL.appendingPathComponent("artifacts.py"),
            finalGateVerifierSupportURL.appendingPathComponent("swift_logs.py"),
            finalGateVerifierSupportURL.appendingPathComponent("evidence_basic.py"),
            finalGateVerifierSupportURL.appendingPathComponent("evidence_test_suites.py"),
            finalGateVerifierSupportURL.appendingPathComponent("evidence_oracles.py"),
            finalGateVerifierSupportURL.appendingPathComponent("readex_boundary.py"),
            finalGateVerifierSupportURL.appendingPathComponent("verifier.py"),
            finalGateVerifierSupportURL.appendingPathComponent("cli.py"),
            scriptsURL.appendingPathComponent("msp_final_gate_preflight.py"),
            scriptsURL.appendingPathComponent("msp_pressure_evidence.py"),
            scriptsURL.appendingPathComponent("msp_pressure_contract.py"),
            scriptsURL.appendingPathComponent("msp_pressure_json_support.py"),
            scriptsURL.appendingPathComponent("msp_pressure_event_log.py"),
            scriptsURL.appendingPathComponent("msp_pressure_event_fields.py"),
            scriptsURL.appendingPathComponent("msp_pressure_exec_session_contract.py"),
            scriptsURL.appendingPathComponent("msp_pressure_feedback_evidence.py"),
            scriptsURL.appendingPathComponent("msp_pressure_feedback_json.py"),
            scriptsURL.appendingPathComponent("msp_pressure_model_provenance.py"),
            scriptsURL.appendingPathComponent("msp_pressure_prompt_delivery.py"),
            scriptsURL.appendingPathComponent("msp_pressure_provider_smoke.py"),
            scriptsURL.appendingPathComponent("msp_pressure_matrix_summary.py")
        ].map { try String(contentsOf: $0, encoding: .utf8) }.joined(separator: "\n")

        for required in [
            "REQUIRED_STEPS",
            "SWIFTPM_SCRATCH_STEPS",
            "debian12-noninteractive-oracle",
            "real-model-pressure-preflight-hardening",
            "real-model pressure preflight checks passed",
            "REQUIRED_PRESSURE_SUITES",
            "readex_boundary_report",
            "verify_readex_boundary",
            "verify_readex_boundary_root",
            "Readex boundary report",
            "Readex boundary report root does not match final gate repository_root",
            "Readex boundary report {key} does not match current repository scan",
            "dirty_snapshot_status",
            "host-backed",
            "exec-session",
            "mixed-backend",
            "photosorter-virtual",
            "photosorter-exec-session",
            "python-subprocess-policy-tests",
            "exec_session_stress_report",
            "exec-session-stress/exec-session-stress-report.json",
            "exec-session stress command does not use final-gate scratch path",
            "exec-session stress scratch_root is outside report directory",
            "exec-session stress command scratch path does not match scratch_root",
            "exec-session stress exit_code is not 0",
            "exec-session stress skipped_test_count is not 0",
            "exec-session stress Swift log",
            "verify_swift_report_log_counts(\"exec-session stress\"",
            "log command does not use final-gate scratch path",
            "log command scratch path is not step scoped",
            "swiftpm-scratch/{step}",
            "open_source_release_dry_run_report",
            "open-source-release-dry-run/open-source-release-dry-run-report.json",
            "open-source release dry-run report",
            "msp-open-source-release-dry-run",
            "schema_version",
            "release_candidate_contract",
            "publishable_file_set_rule",
            "required_checks",
            "required_examples",
            "open-source release dry-run required_checks do not match required coverage",
            "open-source release dry-run commands do not cover every required copied-tree SwiftPM test",
            "open-source release dry-run command check_ids do not cover every required check",
            "open-source release dry-run command {index} log is outside report directory",
            "open-source release dry-run command {index} evidence_report is outside report directory",
            "dynamic_embedded_cpython_swift_tests_report",
            "dynamic-embedded-cpython-swift-tests/dynamic-embedded-cpython-swift-tests-report.json",
            "dynamic embedded CPython Swift tests report",
            "msp-dynamic-embedded-cpython-swift-tests",
            "dynamic embedded CPython skipped_test_count is not 0",
            "dynamic embedded CPython required_test_classes does not match required coverage",
            "focused_test_suites_ledger_report",
            "focused-test-suites-ledger/focused-test-suites-ledger-report.json",
            "focused test suites ledger report",
            "msp-focused-test-suites-ledger",
            "focused test suites ledger required_steps do not match required focused coverage",
            "focused test suites ledger entries do not cover every required focused step in order",
            "focused test suites ledger {step} log does not match final gate step_logs",
            "focused test suites ledger {step} evidence_artifact does not match final gate evidence_artifacts",
            "focused test suites ledger {step} command does not use final-gate scratch path",
            "focused test suites ledger {step} command scratch path is not step scoped",
            "$OUT_DIR/swiftpm-scratch/{step}",
            "_with_final_gate_scratch_contract",
            "python-vfs-path-semantics-tests",
            "MSPPythonHostProcessVFSTestsBytesAndMetadata/testHostProcessPythonTempfileAndDirFDStayVirtual",
            "MSPPythonHostProcessVFSTestsBytesAndMetadata/testHostProcessPythonEntrypointsAndPathlibStayVirtual",
            "MSPPythonHostProcessVFSTestsSecurity/testHostProcessPythonVFSGuardsImportsLinksPathStringsAndRealPathEscapes",
            "Python VFS tempfile, dir_fd, pathlib, and escape-guard semantics stay virtual",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonNestedPythonSubprocessTracebacksStayVirtual",
            "nested Python subprocess traceback paths stay virtual",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonNestedPythonScriptSubprocessUsesVirtualCWDArgumentsAndSiblingFiles",
            "nested Python script subprocesses preserve virtual cwd, argv, sys.path[0], and sibling-file access",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonPopenFileTargetsAndValidationUseControlledSubprocessBroker",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonPopenPipeChainsAndNestedPythonUseControlledSubprocessBroker",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonPopenLifecycleTimeoutsAndConcurrencyUseControlledSubprocessBroker",
            "Python subprocess Popen stdout/stderr pipes are iterable file-like objects across streaming, bytes, memory, and deferred nested-Python paths",
            "Python subprocess Popen pipe objects expose CPython-compatible file-like metadata, readable/writable/seekable/isatty semantics, and context-manager close semantics",
            "Python subprocess Popen communicate caches completed stdout/stderr results across repeated calls, wait-then-communicate, manual-read-before-communicate, and nested-Python paths",
            "Python subprocess Popen exposes CPython-compatible pid, repr, and send_signal lifecycle semantics without leaking MSP internal class names",
            "Python subprocess.run and Popen expose CPython-compatible text-mode behavior and reject conflicting text/universal_newlines arguments",
            "Python subprocess.run and Popen stdout/stderr writable file targets write through the MSP virtual filesystem",
            "Python subprocess.run and Popen reject invalid stream/stdin targets before child execution with CPython-compatible diagnostics",
            "Python subprocess TimeoutExpired exceptions preserve the caller command in cmd without leaking MSP session ids",
            "Python subprocess TimeoutExpired exceptions preserve CPython-compatible partial stdout/stderr bytes for run and communicate timeouts",
            "MSPPythonSubprocessBrokerTests/testWaitTimeoutIncludesUnreadOutputWithoutConsumingIt",
            "MSPPythonSubprocessBrokerTests/testSessionIncludesReturnedResultOutputWhenRunnerDoesNotStream",
            "MSPPythonSubprocessBrokerTests/testSessionMergesReturnedStderrWhenRunnerDoesNotStream",
            "Python subprocess Popen sessions preserve returned stdout/stderr for non-streaming runners",
            "python-script-traceback-path-tests",
            "MSPPythonHostProcessTracebackTests/testHostProcessPythonScriptEntrypointTracebackUsesVirtualScriptPath",
            "MSPPythonHostProcessTracebackTests/testPythonOutputPathSanitizerHidesEncodedFileURLs",
            "MSPPythonHostProcessTracebackTests/testPythonStreamingOutputSanitizerKeepsSplitInternalPathsUntilComplete",
            "Python temporary script entrypoint traceback paths stay virtual",
            "encoded file URL output paths stay virtual",
            "split streaming output paths stay virtual",
            "external-runner-path-virtualization-tests",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualAbsolutePathArgumentsToHostPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualPathsInsideOptionValues",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualPathsInEnvironmentValuesToHostPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualPathsInEnvironmentPathListsToHostPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualFileURLsToHostFileURLs",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerLaunchFailuresKeepPathsVirtual",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerLaunchFailuresDoNotLeakHostOnlyExecutablePaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerSanitizesHostOnlyExecutablePathsInOutput",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerSanitizesVersionOutputPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerVirtualizesEnvironmentAndOutputPaths",
            "host-process external runner maps virtual absolute path arguments to host paths",
            "host-process external runner maps virtual paths embedded in option values",
            "host-process external runner maps virtual paths carried in environment values to host paths",
            "host-process external runner maps virtual paths carried in environment path lists to host paths",
            "host-process external runner maps virtual file URLs to host file URLs",
            "host-process external runner launch failures keep paths virtual",
            "host-process external runner launch failures do not leak host-only executable paths",
            "host-process external runner output does not leak host-only executable paths or encoded host-only file URLs, and does not duplicate model-visible PATH entries",
            "host-process external runner version output paths stay virtual",
            "host-process external runner environment and stdout/stderr paths stay virtual",
            "mixed-workspace-lazy-remote-tests",
            "ModelShellProxyMixedWorkspaceTests/testShellPythonAndSubprocessShareMixedHostAndVirtualBackends",
            "ModelShellProxyMixedWorkspaceTests/testShellRangeReadsLazyRemoteMountBeforePythonFullRead",
            "mixed workspace host/virtual consistency plus Python subprocess remote/lazy range-read seed",
            "workspace-ui-snapshot-consistency-tests",
            "MSPPlaygroundWorkspaceProfileTests",
            "photosorter-overlay-view-consistency-tests",
            "PhotoLibraryWorkspaceFileSystemPathTests/testPhotoLibraryWorkspaceOverlayKeepsTreeLookupReadPreviewAndRestoreConsistent",
            "photosorter-ui-preview-cache-consistency-tests",
            "MSPPlaygroundViewModelTests/testWorkspaceMediaPreviewInvalidatesCachedContentWhenWorkspaceCacheVersionChanges",
            "PhotoSorter UI preview cache invalidates when the workspace view version changes",
            "photosorter-ui-thumbnail-cache-consistency-tests",
            "MSPPlaygroundShellRuntimePreviewTests/testThumbnailCacheKeyIncludesWorkspaceCacheVersion",
            "PhotoSorter UI thumbnail cache keys include the workspace view version",
            "full_swift_test_suite_report",
            "full-swift-test-suite/full-swift-test-suite-report.json",
            "full Swift test suite report",
            "msp-full-swift-test-suite",
            "full Swift test suite skipped_test_count is not 0",
            "full Swift test suite command is not unfiltered swift test",
            "full Swift test suite environment {key} is not 1",
            "MSP_RUN_CORE100_ORACLE",
            "full Swift test suite environment did not require linux-external PTY oracle backend",
            "full Swift test suite required_log_fragments missing: {required}",
            "full_agentbridge_parity_matrix_report",
            "full-agentbridge-parity-matrix/full-agentbridge-parity-matrix-report.json",
            "full AgentBridge parity matrix report",
            "msp-full-agentbridge-parity-matrix",
            "full AgentBridge parity matrix skipped_test_count is not 0",
            "full AgentBridge parity matrix command does not use final-gate scratch path",
            "full AgentBridge parity matrix scratch_root is outside report directory",
            "full AgentBridge parity matrix command scratch path does not match scratch_root",
            "full AgentBridge parity matrix required_capability_buckets do not match contract",
            "full AgentBridge parity matrix command filter does not match swift_filter",
            "full AgentBridge parity matrix test_class_count does not match test_classes",
            "full AgentBridge parity matrix declared_test_count does not match test_classes",
            "full AgentBridge parity matrix swift_filter does not match test_classes",
            "full AgentBridge parity matrix capability bucket references unknown test class",
            "full AgentBridge parity matrix capability bucket declared_test_count does not match classes",
            "full AgentBridge parity matrix swift_filter does not match discovery test_filter",
            "full AgentBridge parity matrix capability_buckets do not match discovery",
            "full AgentBridge parity matrix test_classes do not match discovery",
            "full AgentBridge parity matrix Swift log does not mention discovered test class",
            "full AgentBridge parity matrix environment MSP_CODEX_APPLY_PATCH_DYLIB is missing",
            "full AgentBridge parity matrix source_currentness did not pass",
            "core100_noninteractive_oracle_report",
            "debian12_noninteractive_oracle_report",
            "debian12_linux_pty_oracle_report",
            "real_model_pressure_matrix_report",
            "real-model-pressure-matrix/pressure-matrix-report.json",
            "real_model_pressure_suite_reports",
            "real_model_pressure_preflight_report",
            "verify_real_model_pressure_preflight",
            "verify_report_out_dir",
            "EXPECTED_EVIDENCE_RELATIVE_PATHS",
            "require_canonical_artifact_path",
            "does not match final gate canonical path",
            "final gate out_dir does not match report directory",
            "step_logs keys do not match required steps",
            "evidence_artifacts keys do not match required evidence",
            "REQUIRED_PREFLIGHT_CASE_LABELS",
            "final_gate_wrong_model",
            "matrix_final_gate_active_requires_out_dir",
            "matrix_partial_suite_list",
            "matrix_duplicate_suite_list",
            "playground_bad_prompt_contract",
            "photosorter_bad_prompt_contract",
            "playground_inherited_disable_reset",
            "photosorter_inherited_disable_reset",
            "real-model pressure preflight report",
            "real-model pressure preflight runner_kinds",
            "real-model pressure preflight case_count does not match required coverage",
            "real-model pressure preflight case_labels do not match required coverage",
            "real-model pressure preflight cases do not include every required runner kind",
            "real-model pressure preflight cases do not include every required case label",
            "PREFLIGHT_RUNNER_PATH_BY_KIND",
            "PREFLIGHT_CASE_CONTRACTS",
            "runner_kind does not match label contract",
            "runner path does not match runner_kind contract",
            "override_keys do not match label contract",
            "expected_stderr does not match label contract",
            "forbidden_stdout does not match label contract",
            "forbidden_stderr does not match label contract",
            "crossed a forbidden stderr startup boundary",
            "failedCaseCount",
            "selectedCaseCount",
            "Core100 noninteractive oracle did not pass all 905 fixture cases",
            "Core100 noninteractive oracle covers fewer than 100 command buckets",
            "REQUIRED_CORE100_COMMAND_BUCKETS",
            "Core100 noninteractive oracle missing required command bucket",
            "REQUIRED_CORE100_CASE_IDS",
            "Core100 noninteractive passedCaseIDs does not contain 905 unique cases",
            "Core100 noninteractive oracle missing required passed case id",
            "LINUX_CHARACTER_ORACLE_REPORT_KEYS",
            "LINUX_CHARACTER_ORACLE_SCOPE",
            "linux_character_oracle_alignment_summary",
            "verify_linux_character_oracle_alignment",
            "linux_character_oracle_alignment",
            "linux-character-level-oracle-alignment",
            "all_counts_present",
            "all_character_oracle_cases_passed",
            "compatibility_adjustments_empty",
            "did not prove all oracle counts",
            "did not prove all character oracle cases passed",
            "did not prove empty compatibility adjustments",
            "selected and passed case counts do not match",
            "final gate linux_character_oracle_alignment does not match oracle evidence",
            "REQUIRED_DEBIAN_NONINTERACTIVE_CASE_IDS",
            "REQUIRED_DEBIAN_PTY_CASE_IDS",
            "Debian noninteractive passedCaseIDs does not contain 50 unique cases",
            "Debian noninteractive oracle missing required passed case id",
            "live noninteractive Linux VPS oracle missing required passed case id",
            "Debian Linux PTY passedCaseIDs does not contain 157 unique cases",
            "Debian Linux PTY oracle missing required passed case id",
            "did not pass all 50 fixture cases",
            "did not pass all 157 fixture cases",
            "looks_like_regular_linux",
            "model feedback does not say it looks like regular Linux",
            "can_distinguish_from_regular_linux",
            "leaked_internal_paths",
            "suspicious_outputs",
            "notes",
            "EXPECTED_FEEDBACK_FIELDS",
            "require_feedback_schema",
            "missing required field(s)",
            "has unexpected field(s)",
            ".notes must be a non-empty string",
            "feedback.{key} does not match event_log evidence",
            "scanner_leaks",
            "provider_smoke",
            "prompt_contract",
            "prompt_delivery",
            "model_response_provenance",
            "model_response_provenance_summary",
            "model_response_completed",
            "model_final_answer_provenance",
            "provider_stream_final_answer",
            "request_layer",
            "runtime_provider",
            "request_layers",
            "request_layers count does not match model_request_built.count",
            "request_layers are not all runtime_provider",
            "model_request_layer",
            "model_request ref is missing",
            "model_request ref was not previously built",
            "model_request_sequence",
            "model_request_run_id",
            "completed_model_request_layers",
            "completed_model_request_refs",
            "final_answer_model_request_layers",
            "final_answer_model_request_refs",
            "final_answer_request_last_user_input_sha256s",
            "final_answer_text_sha256s",
            "text_hash_algorithm",
            "text_sha256",
            "provenance_text_hash_algorithm",
            "provenance_text_sha256",
            "final_answer[{answer_number}].response_id does not match provenance event",
            "final_answer[{answer_number}].provenance_text_length does not match provenance event",
            "final_answer[{answer_number}].text_sha256 does not match text",
            "final_answer[{answer_number}].text_sha256 does not match provenance event",
            "final_answer[{answer_number}].provenance_text_sha256 does not match provenance event",
            "MODEL_RESPONSE_PROVENANCE_CORE_FIELDS",
            "compare_event_log_core_fields",
            "validate_matrix_model_response_provenance",
            "required_final_sentinel_answer_indices",
            "feedback answer must be a JSON object",
            "event_log artifact is outside suite report directory",
            "EXPECTED_EVENT_LOG_RELATIVE_PATH",
            "blank JSONL event line is not allowed",
            "event must have a non-empty string event name",
            "event timestamp is missing",
            "event timestamp must be a string",
            "event timestamp must be an ISO-8601 UTC timestamp",
            "event timestamp moved backwards",
            "event fields are missing",
            "event fields must be a JSON object",
            "event field values must be strings",
            "event has unexpected top-level field(s)",
            "TEXT_LIKE_EVENT_FIELD_NAMES",
            "model-visible text field is not registered for event",
            "stdout",
            "stderr",
            "output_text",
            "visible_text",
            "event_log artifact does not match canonical suite path",
            "provider_smoke_artifact_is_under_base_dir",
            "provider_smoke.{key} artifact is outside suite report directory",
            "EXPECTED_PROVIDER_SMOKE_RELATIVE_PATHS",
            "provider_smoke_artifact_matches_canonical_path",
            "provider_smoke.{key} artifact does not match canonical suite path",
            "model reported {report_label} was not quoted from observed output",
            "model negative Linux feedback did not include suspicious_outputs",
            "\"leaked internal path\"",
            "\"suspicious output\"",
            "expected no more than",
            "above expected pressure turn count",
            "completion final_answer has no required sentinel",
            "completion sentinels share one final answer",
            "completion sentinel appears in multiple final answers",
            "provider_smoke.checked is not true",
            "artifact does not exist",
            "require_artifact_under_report_root",
            "outside final gate report directory",
            "provider_smoke.expected_output is not a dynamic MSP_PROVIDER_OK nonce",
            "provider_smoke actual output does not match expected output",
            "path does not match canonical prompt file",
            "sha256 does not match canonical prompt file",
            "prompt_sha256s does not match canonical prompt file",
            "prompt_delivery auto_submit prompt_index sequence does not match prompt file order",
            "auto_submit_count does not match required pressure turn count",
            "request_last_user_input_sha256",
            "model_request_last_user_input_sha256s",
            "final_answer_text_sha256s",
            "model_request_prompt_match_indices",
            "model_request_last_user_input_sha256s do not match canonical prompt order",
            "model_request_prompt_match_indices does not cover every prompt",
            "final_answer_request_last_user_input_sha256s do not match canonical prompt order",
            "required_final_sentinels does not match final gate contract",
            "response artifact id is missing or not a string",
            "response artifact object is not response",
            "provider_smoke.request_model is not",
            "provider_smoke request artifact model is not",
            "final gate model is not",
            "final gate model_matches_required is not true",
            "final gate model_failures",
            "pressure matrix required_model is not",
            "pressure matrix model is not",
            "pressure matrix model_matches_required is not true",
            "pressure matrix model_failures",
            "pressure matrix missing_suites",
            "suite report required_model is not",
            "suite report model is not",
            "suite report model_matches_required is not true",
            "suite report model_failures",
            "model_request_built.expected_count must be positive",
            "model_request_built.expected_count does not match required pressure turn count",
            "model_request_built.count is below expected_count",
            "model_request_built.models is not exactly",
            "model_request_built.all_match_required is not true",
            "validate_matrix_model_request_built",
            "validate_matrix_provider_smoke",
            "validate_matrix_prompt_contract",
            "validate_matrix_prompt_delivery",
            "validate_matrix_feedback",
            "prefix = f\"pressure matrix {suite} model_request_built\"",
            "pressure matrix {suite} name does not match suite id",
            "pressure matrix {suite} {key} does not match suite report evidence",
            "pressure matrix {suite} scanner_leaks does not match suite report evidence",
            "event_log did not execute workspace commands",
            "event_log runtime_error observed",
            "pressure matrix required_suites does not match final gate contract",
            "pressure matrix suites keys do not match required pressure suites",
            "swift_filters",
            "ModelShellProxyExecSessionStressTests",
            "ModelShellProxyExecSessionPTYStressTests",
            "ModelShellProxyReleaseGateAuxiliarySourceGuardTests",
            "ModelShellProxyReleaseGateConformanceTests",
            "ModelShellProxyReleaseGatePreflightConformanceTests",
            "ModelShellProxyReleaseGateVerifierSourceGuardTests"
        ] {
            XCTAssertTrue(finalGateVerifier.contains(required), "final gate verifier missing \(required)")
        }
    }
}
