import Foundation
import XCTest

final class ModelShellProxyProfileConformanceTests: XCTestCase {
    func testModelWorkspaceExecutionSDKProfileReferencesLiveOracleAssets() throws {
        let rootURL = try ModelShellProxyConformanceSupport.packageRoot()
        let profileURL = rootURL
            .appendingPathComponent("Spec")
            .appendingPathComponent("Profiles")
            .appendingPathComponent("MSPModelWorkspaceExecutionSDKProfile.md")
        let chineseProfileURL = rootURL
            .appendingPathComponent("Spec")
            .appendingPathComponent("Profiles")
            .appendingPathComponent("MSPModelWorkspaceExecutionSDKProfile.zh-CN.md")
        let profile = try String(contentsOf: profileURL, encoding: .utf8)
        let chineseProfile = try String(contentsOf: chineseProfileURL, encoding: .utf8)
        let normalizedProfile = profile
            .split(whereSeparator: \.isWhitespace)
            .joined(separator: " ")
        let normalizedChineseProfile = chineseProfile
            .split(whereSeparator: \.isWhitespace)
            .joined(separator: " ")

        let requiredText = [
            "MSPModelWorkspaceExecutionSDKProfile.zh-CN.md",
            "must not modify Readex source code",
            "Linux character-level oracle",
            "MSP_PLAYGROUND_MODEL_BASE_URL",
            "MSP_PLAYGROUND_MODEL_API_KEY",
            "MSP_PLAYGROUND_MODEL",
            "The exec-session gate report must mark that narrower scope explicitly so it cannot be mistaken for total project completion",
            "The exec-session gate and standalone real-model pressure matrix both refuse any run where `MSP_PLAYGROUND_MODEL` is not exactly `gpt-5.5`",
            "The matrix report must include `required_model`, `model`, `model_matches_required`, and `model_failures`",
            "`final-exec-session-gate-report.json` must include the ordered step list",
            "`completion_scope: exec-session-release-gate`, `not_final_msp_open_source_release_gate: true`",
            "`missing_final_gate_classes`, `required_model`, `model`",
            "Because this is not the overall MSP open-source release gate",
            "`missing_final_gate_classes` must stay non-empty",
            "`remote-backed-workspace-conformance`",
            "`lazy-materialized-workspace-conformance`",
            "`full-ui-preview-thumbnail-cache-e2e-conformance`",
            "`readex-migration-compatibility-conformance`",
            "`model_matches_required`, `model_failures`, and evidence artifact paths",
            "open-source release dry-run report",
            "The open-source release dry-run report must prove that the current publishable worktree surface was copied into a release tree",
            "`open-source-release-dry-run-report.json`",
            "`open_source_release_dry_run_report`",
            "Conformance/Scripts/run_open_source_release_dry_run.py",
            "dynamic embedded CPython Swift tests report",
            "full AgentBridge parity matrix report",
            "run_full_agentbridge_parity_matrix.sh",
            "`Tests/Swift/Unit/MSPAgentBridge`",
            "zero skipped tests",
            "`MSPCPythonEngineWorkspaceTests`, `MSPCPythonEngineSubprocessTests`, `MSPCPythonEngineControlledSubprocessMatrixTests`, `MSPCPythonEngineControlledSubprocessCommunicationTests`, `MSPCPythonEngineControlledSubprocessFileTargetTests`, `MSPCPythonEngineControlledSubprocessStreamingTests`, `MSPCPythonEngineControlledSubprocessSignalTests`, `MSPCPythonEngineSubprocessLifecycleTests`, `MSPCPythonEngineSubprocessPressureMatrixTests`, and `MSPCPythonEnginePressureTests`",
            "provider smoke prompt, expected output, or nonce are overridden",
            "run-real-model-pressure.sh",
            "run-shell-diagnostic.sh",
            "verify-real-model-pressure-log.py",
            "run_final_exec_session_release_gate.sh",
            "cannot distinguish MSP from a real Linux workspace",
            "Python and shell see the same workspace",
            "subprocesses do not escape the workspace",
            "UI file trees, previews, thumbnails, caches, and path lookup",
            "ModelShellProxyMixedWorkspaceTests.swift",
            "remote/lazy-style mounted backend",
            "ModelShellProxyMixedWorkspaceTests/testShellPythonAndSubprocessShareMixedHostAndVirtualBackends",
            "direct `/docs`, direct `/tmp`, and virtual `/media`",
            "`readFileRange` before Python performs a full virtual read",
            "not yet the full remote-backed or lazy-materialized workspace release certification",
            "mixed host `/docs` + `/tmp` + virtual `/media` read/write/delete/subprocess consistency coverage",
            "ModelShellProxyMixedWorkspaceTests/testShellRangeReadsLazyRemoteMountBeforePythonFullRead",
            "shell and Python-subprocess head/tail reads through `readFileRange`",
            "MSPPlaygroundViewModelTests/testWorkspaceMediaPreviewInvalidatesCachedContentWhenWorkspaceCacheVersionChanges",
            "PhotoSorter UI preview-cache invalidation slice",
            "MSPPlaygroundShellRuntimePreviewTests/testThumbnailCacheKeyIncludesWorkspaceCacheVersion",
            "PhotoSorter UI thumbnail-cache key slice",
            "MSPPythonHostProcessVFSTestsBytesAndMetadata/testHostProcessPythonTempfileAndDirFDStayVirtual",
            "MSPPythonHostProcessVFSTestsBytesAndMetadata/testHostProcessPythonEntrypointsAndPathlibStayVirtual",
            "MSPPythonHostProcessVFSTestsSecurity/testHostProcessPythonVFSGuardsImportsLinksPathStringsAndRealPathEscapes",
            "host-process Python keeps `tempfile`, `dir_fd`, entrypoint",
            "MSPPythonHostProcessTracebackTests/testHostProcessPythonScriptEntrypointTracebackUsesVirtualScriptPath",
            "MSPPythonHostProcessTracebackTests/testPythonOutputPathSanitizerHidesEncodedFileURLs",
            "MSPPythonHostProcessTracebackTests/testPythonStreamingOutputSanitizerKeepsSplitInternalPathsUntilComplete",
            "Python output-path virtualization coverage",
            "virtual `__file__`, virtual `sys.argv[0]`, and virtual traceback paths",
            "encoded `file://` URL output maps back to",
            "long streaming output cannot leak an internal path",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualAbsolutePathArgumentsToHostPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualPathsInsideOptionValues",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualPathsInEnvironmentValuesToHostPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualPathsInEnvironmentPathListsToHostPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualFileURLsToHostFileURLs",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerLaunchFailuresKeepPathsVirtual",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerLaunchFailuresDoNotLeakHostOnlyExecutablePaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerSanitizesHostOnlyExecutablePathsInOutput",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerSanitizesVersionOutputPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerVirtualizesEnvironmentAndOutputPaths",
            "external runner path virtualization coverage",
            "host-process external commands map virtual absolute path arguments to host paths",
            "host-process external commands map virtual paths embedded in option values",
            "host-process external commands map virtual paths carried in environment values to host paths",
            "host-process external commands map virtual paths carried in environment path lists to host paths",
            "host-process external commands map virtual file URLs to host file URLs",
            "host-process external commands keep launch-failure paths virtual",
            "host-process external commands do not leak host-only executable paths when launch fails",
            "host-process external commands do not leak host-only executable paths or encoded host-only file URLs in stdout or stderr, or duplicate model-visible PATH entries",
            "host-process external commands keep static version output paths virtual",
            "host-process external commands expose virtual `PWD`, virtual `TMPDIR`, virtual `MSP_WORKSPACE_ROOT`",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonNestedPythonSubprocessTracebacksStayVirtual",
            "`subprocess.run` and `Popen(..., stdin=PIPE)`",
            "preserve virtual traceback paths for nested Python processes",
            "MSPPythonSubprocessBrokerTests/testSessionIncludesReturnedResultOutputWhenRunnerDoesNotStream",
            "MSPPythonSubprocessBrokerTests/testSessionMergesReturnedStderrWhenRunnerDoesNotStream",
            "MSPPythonSubprocessBrokerTests/testWaitTimeoutIncludesUnreadOutputWithoutConsumingIt",
            "Python subprocess Popen sessions preserve returned stdout/stderr for non-streaming runners",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonPopenFileTargetsAndValidationUseControlledSubprocessBroker",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonPopenPipeChainsAndNestedPythonUseControlledSubprocessBroker",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonPopenLifecycleTimeoutsAndConcurrencyUseControlledSubprocessBroker",
            "Python subprocess Popen stdout/stderr pipes are iterable file-like objects across streaming, bytes, memory, and deferred nested-Python paths",
            "Python subprocess Popen pipe objects expose CPython-compatible file-like metadata, readable/writable/seekable/isatty semantics, and context-manager close semantics",
            "Python subprocess Popen communicate caches completed stdout/stderr results across repeated calls, wait-then-communicate, manual-read-before-communicate, and nested-Python paths",
            "Python subprocess Popen exposes CPython-compatible pid, repr, and send_signal lifecycle semantics without leaking MSP internal class names",
            "Python subprocess.run and Popen expose CPython-compatible text-mode behavior and reject conflicting text/universal_newlines arguments",
            "Python subprocess.run and Popen stdout/stderr writable file targets write through the MSP virtual filesystem",
            "Python subprocess.run and Popen reject invalid stream/stdin targets before child execution with CPython-compatible diagnostics",
            "Python subprocess TimeoutExpired exceptions preserve the caller command in cmd without leaking MSP session ids",
            "Python subprocess TimeoutExpired exceptions preserve CPython-compatible partial stdout/stderr bytes for run and communicate timeouts",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonNestedPythonScriptSubprocessUsesVirtualCWDArgumentsAndSiblingFiles",
            "nested Python script subprocesses in the host-process runtime",
            "script-sibling file access",
            "MSPCPythonEngineSubprocessTests/testCPythonEngineNestedPythonSubprocessTracebacksStayVirtualWhenLibraryIsAvailable",
            "the real embedded CPython runtime",
            "nested child-Python traceback virtualization coverage",
            "MSPCPythonEngineSubprocessTests/testCPythonEngineNestedPythonScriptSubprocessUsesVirtualCWDArgumentsAndSiblingFilesWhenLibraryIsAvailable",
            "nested script `cwd`/argument/sibling-file coverage",
            "MSPCPythonEngineWorkspaceTests/testCPythonEngineTempfileAndDirFDStayVirtualWhenLibraryIsAvailable",
            "embedded `tempfile`/`dir_fd` virtual workspace coverage",
            "Command-specific, script-specific, path-specific, album-specific, or test-specific patches are not acceptable as final fixes",
            "Final delivery may not keep known mismatches",
            "may not explain them away as normal sandbox behavior",
            "include a boolean `passed` field, a string-array `failures` field",
            "`required_model`, `model`, `model_matches_required`, `model_failures`",
            "`model_request_built` evidence block proving that the main pressure-turn",
            "`expected_count`",
            "`expected_count` must exactly equal the required prompt turns",
            "`count` must",
            "forges or undercounts the required prompt turns",
            "`provider_smoke` evidence block with `checked: true`",
            "`request_model`, `request_model_matches_required`, `expected_output`, and `actual_output`",
            "actual `model` field inside the provider-smoke request artifact must both be exactly `gpt-5.5`",
            "`expected_output` and `actual_output`",
            "verifiers must reopen the referenced provider-smoke request and response artifacts",
            "must also refuse suite-level weakening overrides",
            "`MSP_PLAYGROUND_PRESSURE_REQUIRE_PYTHON=0`",
            "`MSP_PLAYGROUND_PRESSURE_RUN_SHELL_DIAGNOSTIC=0`",
            "`MSP_PLAYGROUND_PRESSURE_RUN_PYTHON_ORACLE=0`",
            "`MSP_PLAYGROUND_PRESSURE_RESET_APP=0`",
            "`MSP_PHOTOSORTER_PRESSURE_REQUIRE_CPYTHON=0`",
            "`MSP_PHOTOSORTER_PRESSURE_RESET_APP=0`",
            "disabled Python, shell diagnostic, Python oracle, embedded CPython, or fresh-app-reset checks",
            "The matrix verifier must honor a suite report's `passed: false` or non-empty `failures`"
        ]
        for text in requiredText {
            XCTAssertTrue(normalizedProfile.contains(text), "missing profile requirement: \(text)")
        }

        let requiredChineseText = [
            "MSP 要成为一套通用的“模型工作区执行 SDK”",
            "MSP 不是 PhotoSorter 专用 shell，也不是 Readex 的临时复刻",
            "当前阶段禁止修改 Readex 源码",
            "所有实现、实验、测试、压测、fixture、临时脚本、调试入口，都必须只发生在 MSP 仓库内",
            "MSP 必须支持真实宿主目录工作区",
            "MSP 必须支持虚拟工作区",
            "MSP 必须支持混合工作区",
            "MSP 必须有完整路径映射",
            "MSP 必须让 Python 进入同一套工作区语义",
            "MSP 必须让 Python 子进程一致",
            "MSP policy 必须是通用 SDK 能力",
            "MSP 必须保证 UI 和运行时一致",
            "必须有混合后端验收",
            "当前已经提交的混合后端 conformance 种子",
            "稳定操作真实 `/docs`、真实 `/tmp` 和虚拟 `/media`",
            "remote/lazy 风格的 mounted backend",
            "shell 和 Python 子进程读取文件头部和尾部时可以先走 `readFileRange`",
            "还不能等同于完整的 remote-backed 或 lazy-materialized workspace release certification",
            "MSPPythonHostProcessVFSTestsBytesAndMetadata/testHostProcessPythonTempfileAndDirFDStayVirtual",
            "MSPPythonHostProcessVFSTestsBytesAndMetadata/testHostProcessPythonEntrypointsAndPathlibStayVirtual",
            "MSPPythonHostProcessVFSTestsSecurity/testHostProcessPythonVFSGuardsImportsLinksPathStringsAndRealPathEscapes",
            "host-process Python 里的 `tempfile`、`dir_fd`、入口脚本、`pathlib` 和逃逸防护",
            "MSPPythonHostProcessTracebackTests/testPythonOutputPathSanitizerHidesEncodedFileURLs",
            "MSPPythonHostProcessTracebackTests/testPythonStreamingOutputSanitizerKeepsSplitInternalPathsUntilComplete",
            "Python 输出路径虚拟化覆盖",
            "`__file__`、`sys.argv[0]` 和 traceback 文件路径都保持工作区虚拟路径",
            "编码后的 `file://` URL 输出会映射回模型看到的工作区路径",
            "长流式输出也不能通过把内部路径拆到多个输出块里来泄露",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualAbsolutePathArgumentsToHostPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualPathsInsideOptionValues",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualPathsInEnvironmentValuesToHostPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualPathsInEnvironmentPathListsToHostPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualFileURLsToHostFileURLs",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerLaunchFailuresKeepPathsVirtual",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerLaunchFailuresDoNotLeakHostOnlyExecutablePaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerSanitizesHostOnlyExecutablePathsInOutput",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerSanitizesVersionOutputPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerVirtualizesEnvironmentAndOutputPaths",
            "external runner 路径虚拟化覆盖",
            "host-process 外部命令会把虚拟绝对路径参数映射成 host path",
            "host-process 外部命令会映射 option value 里的虚拟路径",
            "host-process 外部命令会把环境变量里的虚拟路径映射成 host path",
            "host-process 外部命令会把环境变量路径列表里的虚拟路径映射成 host path",
            "host-process 外部命令会把虚拟 file URL 映射成 host file URL",
            "host-process 外部命令启动失败时路径仍保持虚拟",
            "host-process 外部命令启动失败时不会泄露 host-only executable 路径",
            "host-process 外部命令 stdout/stderr 不会泄露 host-only executable 路径或编码后的 host-only file URL，也不会重复模型可见的 PATH 项",
            "host-process 外部命令静态 version 输出路径也保持虚拟",
            "host-process 外部命令看到虚拟 `PWD`、虚拟 `TMPDIR`、虚拟 `MSP_WORKSPACE_ROOT`",
            "Python 子进程 focused 覆盖",
            "父 Python 可以通过 `subprocess.run` 和 `Popen(..., stdin=PIPE)` 启动子 Python",
            "MSPPythonSubprocessBrokerTests/testSessionIncludesReturnedResultOutputWhenRunnerDoesNotStream",
            "MSPPythonSubprocessBrokerTests/testSessionMergesReturnedStderrWhenRunnerDoesNotStream",
            "Popen session 会保留非 streaming runner 返回的 stdout/stderr",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonPopenFileTargetsAndValidationUseControlledSubprocessBroker",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonPopenPipeChainsAndNestedPythonUseControlledSubprocessBroker",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonPopenLifecycleTimeoutsAndConcurrencyUseControlledSubprocessBroker",
            "Popen stdout/stderr 管道像普通 Python 文件对象一样可迭代",
            "Popen pipe 对象会暴露 CPython 兼容的 file-like 元数据、readable/writable/seekable/isatty 语义和 context manager close 语义",
            "Popen communicate 会缓存已完成的 stdout/stderr 结果，覆盖重复调用、wait 后 communicate、手动读 pipe 后 communicate，以及嵌套 Python 路径",
            "subprocess.run 和 Popen 会暴露 CPython 兼容的文本模式行为，并拒绝冲突的 text/universal_newlines 参数",
            "subprocess.run 和 Popen 的 stdout/stderr 可写文件目标会写回 MSP 虚拟文件系统",
            "subprocess.run 和 Popen 会在启动子进程前拒绝非法 stream/stdin target，并给出 CPython 兼容诊断",
            "TimeoutExpired 异常的 cmd 保持调用方命令，不泄露 MSP session id",
            "TimeoutExpired 异常会为 run 和 communicate timeout 保留 CPython 兼容的 partial stdout/stderr bytes",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonNestedPythonScriptSubprocessUsesVirtualCWDArgumentsAndSiblingFiles",
            "host-process runtime 里的嵌套 Python 脚本子进程",
            "动态嵌入式 CPython 覆盖",
            "真实 embedded CPython runtime",
            "嵌套子 Python traceback 虚拟路径",
            "嵌套 Python 脚本子进程能保持虚拟 `cwd`",
            "同目录文件语义",
            "MSPCPythonEngineWorkspaceTests/testCPythonEngineTempfileAndDirFDStayVirtualWhenLibraryIsAvailable",
            "embedded `tempfile`/`dir_fd` 虚拟工作区语义",
            "PhotoSorter UI 预览缓存随工作区版本失效的切片覆盖",
            "PhotoSorter UI 缩略图缓存 key 随工作区版本隔离的切片覆盖",
            "验收必须覆盖 `pwd`、`ls`、`find`、`xargs`、管道、重定向、脚本文件、临时脚本生成和删除、Python 调子进程、大量文件遍历、大文件读写、错误路径、权限错误、移动、删除、恢复",
            "MSP 的输入输出必须和真 Linux 工作区字符级对齐",
            "模型绝对不能从命令输出、Python 输出、错误信息、路径表现、文件树刷新、预览结果中区分",
            "最终 UI 验收必须使用真实模型，不能用 mock provider",
            "MSP_PLAYGROUND_MODEL_BASE_URL",
            "正式 final gate 和 pressure matrix 都必须要求 `MSP_PLAYGROUND_MODEL` 精确等于 `gpt-5.5`",
            "使用其他模型可以作为本地诊断，但不能作为最终验收或 release evidence",
            "`pressure-matrix-report.json` 必须记录 `required_model`、`model`、`model_matches_required` 和 `model_failures`",
            "即使脱离启动它的 shell runner 单独验 report，也能拒绝错模型跑出来的 matrix evidence",
            "`final-exec-session-gate-report.json` 也必须记录 `required_model`、`model`、`model_matches_required` 和 `model_failures`",
            "final gate report 本身必须足够自解释",
            "final gate 还必须把开源发布 dry-run 作为证据写进报告",
            "`open-source-release-dry-run-report.json`",
            "`open_source_release_dry_run_report`",
            "`missing_final_gate_classes` 必须保持非空",
            "`remote-backed-workspace-conformance`",
            "`lazy-materialized-workspace-conformance`",
            "`full-ui-preview-thumbnail-cache-e2e-conformance`",
            "`readex-migration-compatibility-conformance`",
            "正式 final gate 和 pressure matrix 必须拒绝跳过 provider smoke，也必须拒绝固定 provider smoke 的 prompt、expected output 或 nonce",
            "每个 suite 的 `pressure-report.json` 必须自解释地记录模型身份、主压测请求模型证据和 provider smoke 证据",
            "`model` 必须精确等于 `gpt-5.5`",
            "`model_failures` 必须为空",
            "`model_request_built` 必须记录 `count`、`expected_count`",
            "`expected_count` 必须精确等于这个 suite 必需的 prompt 轮数",
            "`count` 必须大于等于 `expected_count`",
            "主压测请求数量不足",
            "伪造或调低必需 prompt 轮数",
            "主压测事件里的 `model_request_built.model` 必须全部精确等于 `gpt-5.5`",
            "provider smoke 报告里的 `request_model` 以及 request artifact 里的真实 `model` 字段也必须精确等于 `gpt-5.5`",
            "`expected_output` 与 `actual_output` 必须字符级一致",
            "matrix 和 final gate verifier 必须能重新打开这些 request/response artifact",
            "final gate 和 pressure matrix 还必须拒绝把必需子验收关掉的 suite 级环境变量",
            "final gate 还必须把动态嵌入式 CPython Swift 测试作为证据写进报告",
            "final gate 还必须把完整 AgentBridge parity matrix 作为证据写进报告",
            "`run_full_agentbridge_parity_matrix.sh`",
            "`Tests/Swift/Unit/MSPAgentBridge`",
            "ModelShellProxyMixedWorkspaceTests/testShellPythonAndSubprocessShareMixedHostAndVirtualBackends",
            "真实 `/docs` + `/tmp` + 虚拟 `/media` 的读写删除和子进程一致性覆盖",
            "ModelShellProxyMixedWorkspaceTests/testShellRangeReadsLazyRemoteMountBeforePythonFullRead",
            "remote/lazy mixed-workspace 种子覆盖",
            "不能 skip，不能失败",
            "`MSP_PLAYGROUND_PRESSURE_REQUIRE_PYTHON=0`",
            "`MSP_PHOTOSORTER_PRESSURE_REQUIRE_CPYTHON=0`",
            "matrix 自己启动每个 suite 时也必须显式把这些要求设回必需状态",
            "final gate 调用 matrix 时也必须显式把这些要求设回必需状态",
            "任何压测不一致都必须先归因",
            "禁止给某个命令、某段脚本、某条路径、某个相册场景打补丁特判",
            "最终交付不允许保留已知不一致",
            "不允许用“这是沙盒环境所以正常”解释",
            "不允许用特定命令、特定脚本、特定路径的补丁绕过"
        ]
        for text in requiredChineseText {
            XCTAssertTrue(normalizedChineseProfile.contains(text), "missing Chinese profile requirement: \(text)")
        }

        let referencedAssets = [
            "Spec/Profiles/MSPModelWorkspaceExecutionSDKProfile.zh-CN.md",
            "Conformance/ReferenceOutputs/MSPV1Debian12Oracle/noninteractive-cases.json",
            "Conformance/ReferenceOutputs/MSPV1Core100Debian12Oracle/noninteractive-cases.json",
            "Conformance/Fixtures/MSPV1LinuxCommandLayer.parity-cases.json",
            "Conformance/Fixtures/MSPV1LinuxCommandLayer.direct-parity-cases.json",
            "Conformance/Fixtures/MSPV1PythonRuntimeCoverage.json",
            "Conformance/Scripts/check_python_oracle_coverage.py",
            "Conformance/Scripts/cache_beeware_cpython_apple_support.sh",
            "Conformance/Scripts/run_final_exec_session_release_gate.sh",
            "Conformance/Scripts/run_exec_session_stress_gate.sh",
            "Conformance/Scripts/run_dynamic_embedded_cpython_swift_tests.sh",
            "Conformance/Scripts/run_full_agentbridge_parity_matrix.sh",
            "Conformance/Scripts/run_open_source_release_dry_run.py",
            "Conformance/Scripts/verify_readex_boundary.py",
            "Conformance/Scripts/run_debian12_pty_oracle.py",
            "Conformance/Scripts/run_debian12_pty_oracle_container.sh",
            "Conformance/Scripts/verify_debian12_pty_oracle_report.py",
            "Conformance/Scripts/verify_final_exec_session_release_gate_report.py",
            "Tests/Swift/Integration/ModelShellProxy/Conformance",
            "Tests/Swift/Integration/ModelShellProxy/WorkspaceFS/ModelShellProxyMixedWorkspaceTests.swift",
            "Tests/Swift/Unit/MSPPythonRuntime/",
            "Tests/Swift/Unit/MSPPythonEmbeddedRuntime/",
            "Conformance/Scripts/run_real_model_pressure_matrix.sh",
            "Conformance/Scripts/verify_real_model_pressure_matrix.py",
            "Examples/iOS/MSPPlaygroundApp/Tools/E2E/run-real-model-pressure.sh",
            "Examples/iOS/MSPPlaygroundApp/Tools/E2E/run-real-model-e2e.sh",
            "Examples/iOS/MSPPlaygroundApp/Tools/E2E/run-shell-diagnostic.sh",
            "Examples/iOS/MSPPlaygroundApp/Tools/E2E/embed-cpython-xcframework.sh",
            "Examples/iOS/MSPPlaygroundApp/Tools/E2E/check-openai-responses-provider.sh",
            "Examples/iOS/MSPPlaygroundApp/Tools/E2E/verify-real-model-pressure-log.py",
            "Examples/iOS/MSPPlaygroundApp/Tools/E2E/pressure/host-backed-linux-parity-prompts.json",
            "Examples/iOS/MSPPlaygroundApp/Tools/E2E/pressure/exec-session-parity-prompts.json",
            "Examples/iOS/MSPPlaygroundApp/Tools/E2E/pressure/mixed-backend-linux-parity-prompts.json",
            "Examples/iOS/PhotoSorter/Tools/E2E/run-real-model-pressure.sh",
            "Examples/iOS/PhotoSorter/Tools/E2E/run-real-model-e2e.sh",
            "Examples/iOS/PhotoSorter/Tools/E2E/check-openai-responses-provider.sh",
            "Examples/iOS/PhotoSorter/Tools/E2E/pressure/photosorter-virtual-workspace-prompts.json",
            "Examples/iOS/PhotoSorter/Tools/E2E/pressure/photosorter-exec-session-parity-prompts.json"
        ]
        for path in referencedAssets {
            XCTAssertTrue(profile.contains(path), "profile does not reference \(path)")
            XCTAssertTrue(
                FileManager.default.fileExists(atPath: rootURL.appendingPathComponent(path).path),
                "referenced profile asset is missing: \(path)"
            )
        }

        let requiredPythonTestOwners = [
            "Tests/Swift/Unit/MSPPythonRuntime/MSPPythonRuntimeTests.swift",
            "Tests/Swift/Unit/MSPPythonRuntime/MSPPythonHostProcessVFSTests.swift",
            "Tests/Swift/Unit/MSPPythonRuntime/MSPPythonHostProcessSubprocessTests.swift",
            "Tests/Swift/Unit/MSPPythonRuntime/MSPPythonHostProcessSubprocessPopenFileTargetTests.swift",
            "Tests/Swift/Unit/MSPPythonRuntime/MSPPythonHostProcessSubprocessPopenPipeTests.swift",
            "Tests/Swift/Unit/MSPPythonRuntime/MSPPythonHostProcessSubprocessPopenLifecycleTests.swift",
            "Tests/Swift/Unit/MSPPythonRuntime/MSPPythonHostProcessSubprocessShellMatrixTests.swift",
            "Tests/Swift/Unit/MSPPythonEmbeddedRuntime/MSPPythonEmbeddedRuntimeTests.swift",
            "Tests/Swift/Unit/MSPPythonEmbeddedRuntime/MSPCPythonEngineWorkspaceTests.swift",
            "Tests/Swift/Unit/MSPPythonEmbeddedRuntime/MSPCPythonEngineSubprocessTests.swift",
            "Tests/Swift/Unit/MSPPythonEmbeddedRuntime/MSPCPythonEngineControlledSubprocessMatrixTests.swift",
            "Tests/Swift/Unit/MSPPythonEmbeddedRuntime/MSPCPythonEngineControlledSubprocessCommunicationTests.swift",
            "Tests/Swift/Unit/MSPPythonEmbeddedRuntime/MSPCPythonEngineControlledSubprocessFileTargetTests.swift",
            "Tests/Swift/Unit/MSPPythonEmbeddedRuntime/MSPCPythonEngineControlledSubprocessStreamingTests.swift",
            "Tests/Swift/Unit/MSPPythonEmbeddedRuntime/MSPCPythonEngineControlledSubprocessSignalTests.swift",
            "Tests/Swift/Unit/MSPPythonEmbeddedRuntime/MSPCPythonEngineSubprocessLifecycleTests.swift",
            "Tests/Swift/Unit/MSPPythonEmbeddedRuntime/MSPCPythonEngineSubprocessPressureMatrixTests.swift",
            "Tests/Swift/Unit/MSPPythonEmbeddedRuntime/MSPCPythonEnginePressureTests.swift"
        ]
        for path in requiredPythonTestOwners {
            XCTAssertTrue(
                FileManager.default.fileExists(atPath: rootURL.appendingPathComponent(path).path),
                "required Python runtime test owner is missing: \(path)"
            )
        }
    }
}
