import Foundation
import XCTest

final class ModelShellProxyReleaseGateConformanceTests: XCTestCase {
    func testFinalExecSessionReleaseGateRequiresLinuxPTYAndRealGPT55() throws {
        let rootURL = try ModelShellProxyConformanceSupport.packageRoot()
        let finalGateURL = rootURL
            .appendingPathComponent("Conformance")
            .appendingPathComponent("Scripts")
            .appendingPathComponent("run_final_exec_session_release_gate.sh")
        let finalGate = try String(contentsOf: finalGateURL, encoding: .utf8)

        for required in [
            "REQUIRED_MODEL=\"gpt-5.5\"",
            "MSP_PLAYGROUND_MODEL must be exactly $REQUIRED_MODEL",
            "reject_true_env MSP_PLAYGROUND_PRESSURE_SKIP_PROVIDER_SMOKE",
            "reject_true_env MSP_PHOTOSORTER_PRESSURE_SKIP_PROVIDER_SMOKE",
            "reject_zero_env MSP_PLAYGROUND_PRESSURE_REQUIRE_PYTHON",
            "reject_zero_env MSP_PLAYGROUND_PRESSURE_RUN_SHELL_DIAGNOSTIC",
            "reject_zero_env MSP_PLAYGROUND_PRESSURE_RUN_PYTHON_ORACLE",
            "reject_zero_env MSP_PLAYGROUND_PRESSURE_RESET_APP",
            "reject_zero_env MSP_PHOTOSORTER_PRESSURE_REQUIRE_CPYTHON",
            "reject_zero_env MSP_PHOTOSORTER_PRESSURE_RESET_APP",
            "reject_nonempty_env MSP_PLAYGROUND_PROVIDER_CHECK_NONCE",
            "reject_nonempty_env MSP_PLAYGROUND_PROVIDER_CHECK_PROMPT",
            "reject_nonempty_env MSP_PLAYGROUND_PROVIDER_CHECK_EXPECTED_OUTPUT",
            "reject_nonempty_env MSP_PLAYGROUND_PRESSURE_PROMPTS_FILE",
            "reject_nonempty_env MSP_PHOTOSORTER_PRESSURE_PROMPTS_FILE",
            "final-exec-session-release-gate.lock",
            "MSP_FINAL_EXEC_SESSION_GATE_TMPDIR",
            "MSP_CONFORMANCE_TMPDIR",
            "PYTHONDONTWRITEBYTECODE=1",
            "assert_local_hygiene_metadata_clean",
            "final release gate refuses to clean the repository for you",
            "FINAL_GATE_TMPDIR_ALIAS",
            "msp-final-gate-tmp-$STAMP",
            "refusing to run concurrently",
            "export MSP_FINAL_EXEC_SESSION_GATE_ACTIVE=1",
            "SWIFTPM_SCRATCH_ROOT=\"$OUT_DIR/swiftpm-scratch\"",
            "swiftpm_scratch_path()",
            "printf 'command:'",
            "--scratch-path \"$(swiftpm_scratch_path swift-build)\"",
            "--scratch-path \"$(swiftpm_scratch_path exec-command-bridge-tests)\"",
            "resolve_required_cpython_asset",
            "final release gate requires CPython for real-model Python pressure",
            "resolve_required_macos_cpython_asset",
            "final release gate requires macOS CPython for dynamic embedded CPython Swift tests",
            "MSP_CPYTHON_APPLE_SUPPORT_PLATFORMS=macOS Conformance/Scripts/cache_beeware_cpython_apple_support.sh",
            "using cached MSP_CPYTHON_LIBRARY_PATH",
            ".build/msp-cpython-ios-cache",
            ".build/msp-cpython-macos-cache",
            "cache_beeware_cpython_apple_support.sh",
            "check_real_model_pressure_preflight.py",
            "--report \"$OUT_DIR/real-model-pressure-preflight-report.json\"",
            "real-model-pressure-preflight-hardening",
            "run_core100_oracle_conformance.sh",
            "MSP_CORE100_ORACLE_SCRATCH_ROOT=\"$(swiftpm_scratch_path core100-noninteractive-oracle)\"",
            "CORE100_NONINTERACTIVE_ORACLE_SOURCE_REPORT",
            "CORE100_NONINTERACTIVE_ORACLE_REPORT=\"$OUT_DIR/core100-noninteractive-oracle-report.json\"",
            "rm -f \"$CORE100_NONINTERACTIVE_ORACLE_SOURCE_REPORT\"",
            "cp \"$CORE100_NONINTERACTIVE_ORACLE_SOURCE_REPORT\" \"$CORE100_NONINTERACTIVE_ORACLE_REPORT\"",
            "run_exec_session_stress_gate.sh",
            "MSP_EXEC_SESSION_STRESS_GATE_SCRATCH_ROOT=\"$OUT_DIR/exec-session-stress/scratch\"",
            "verify_readex_boundary.py",
            "readex-boundary-check",
            "ModelShellProxyPOSIXCommandSmokeTests/testExecCommandPipeSession",
            "ModelShellProxyExecCommandPipelineTests/testExecCommandBridgePTY",
            "ModelShellProxyExecCommandPipelineTests/testExecCommandBridgeYieldsPTYSessionAndWritesInteractiveStdin",
            "exec-session-stress-gate",
            "python-vfs-path-semantics-tests",
            "MSPPythonHostProcessVFSTestsBytesAndMetadata/testHostProcessPythonTempfileAndDirFDStayVirtual",
            "MSPPythonHostProcessVFSTestsBytesAndMetadata/testHostProcessPythonEntrypointsAndPathlibStayVirtual",
            "MSPPythonHostProcessVFSTestsSecurity/testHostProcessPythonVFSGuardsImportsLinksPathStringsAndRealPathEscapes",
            "Python VFS tempfile, dir_fd, pathlib, and escape-guard semantics stay virtual",
            "python-subprocess-policy-tests",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonSubprocessHonorsCommandPackExclusions",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonNestedPythonSubprocessTracebacksStayVirtual",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonNestedPythonScriptSubprocessUsesVirtualCWDArgumentsAndSiblingFiles",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonPopenFileTargetsAndValidationUseControlledSubprocessBroker",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonPopenPipeChainsAndNestedPythonUseControlledSubprocessBroker",
            "MSPPythonHostProcessSubprocessTests/testHostProcessPythonPopenLifecycleTimeoutsAndConcurrencyUseControlledSubprocessBroker",
            "Python subprocess Popen stdout/stderr pipes are iterable file-like objects across streaming, bytes, memory, and deferred nested-Python paths",
            "Python subprocess Popen pipe objects expose CPython-compatible file-like metadata, readable/writable/seekable/isatty semantics, and context-manager close semantics",
            "Python subprocess Popen communicate caches completed stdout/stderr results across repeated calls, wait-then-communicate, manual-read-before-communicate, and nested-Python paths",
            "Python subprocess Popen exposes CPython-compatible pid, repr, and send_signal lifecycle semantics without leaking MSP internal class names",
            "Python subprocess.run and Popen expose CPython-compatible text-mode behavior and reject conflicting text/universal_newlines arguments",
            "Python subprocess.run and Popen stdout/stderr writable file targets write through the MSP virtual filesystem",
            "Python subprocess.run and Popen reject invalid stream/stdin targets before child execution with CPython-compatible diagnostics",
            "Python subprocess TimeoutExpired exceptions preserve the caller command in cmd without leaking MSP session ids",
            "Python subprocess TimeoutExpired exceptions preserve CPython-compatible partial stdout/stderr bytes for run and communicate timeouts",
            "nested Python script subprocesses preserve virtual cwd, argv, sys.path[0], and sibling-file access",
            "MSPPythonSubprocessBrokerTests/testRunDelegatesToBaseCommandLineRunnerWithVirtualPolicyContext",
            "MSPPythonSubprocessBrokerTests/testWaitTimeoutIncludesUnreadOutputWithoutConsumingIt",
            "MSPPythonSubprocessBrokerTests/testSessionIncludesReturnedResultOutputWhenRunnerDoesNotStream",
            "MSPPythonSubprocessBrokerTests/testSessionMergesReturnedStderrWhenRunnerDoesNotStream",
            "Python subprocess Popen sessions preserve returned stdout/stderr for non-streaming runners",
            "python-script-traceback-path-tests",
            "MSPPythonHostProcessTracebackTests/testHostProcessPythonScriptEntrypointTracebackUsesVirtualScriptPath",
            "MSPPythonHostProcessTracebackTests/testPythonOutputPathSanitizerHidesEncodedFileURLs",
            "MSPPythonHostProcessTracebackTests/testPythonStreamingOutputSanitizerKeepsSplitInternalPathsUntilComplete",
            "Python temporary script entrypoints, __file__, sys.argv[0], traceback paths, encoded file URLs, and split streaming output paths stay virtual",
            "external-runner-path-virtualization-tests",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualAbsolutePathArgumentsToHostPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualPathsInsideOptionValues",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualPathsInEnvironmentValuesToHostPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualPathsInEnvironmentPathListsToHostPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerMapsVirtualFileURLsToHostFileURLs",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerLaunchFailuresKeepPathsVirtual",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerLaunchFailuresDoNotLeakHostOnlyExecutablePaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerSanitizesHostOnlyExecutablePathsInOutput",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerSanitizesVersionOutputPaths",
            "MSPExternalRunnerTests/testHostProcessExternalRunnerVirtualizesEnvironmentAndOutputPaths",
            "host-process external runner maps virtual absolute path arguments to host paths",
            "host-process external runner maps virtual paths embedded in option values",
            "host-process external runner maps virtual paths carried in environment values to host paths",
            "host-process external runner maps virtual paths carried in environment path lists to host paths",
            "host-process external runner maps virtual file URLs to host file URLs",
            "host-process external runner launch failures keep paths virtual",
            "host-process external runner launch failures do not leak host-only executable paths",
            "host-process external runner output does not leak host-only executable paths or encoded host-only file URLs, and does not duplicate model-visible PATH entries",
            "host-process external runner version output paths stay virtual",
            "host-process external runner environment and stdout/stderr paths stay virtual",
            "ModelShellProxyProfileConformanceTests/testModelWorkspaceExecutionSDKProfileReferencesLiveOracleAssets",
            "mixed-workspace-lazy-remote-tests",
            "ModelShellProxyMixedWorkspaceTests/testShellPythonAndSubprocessShareMixedHostAndVirtualBackends",
            "ModelShellProxyMixedWorkspaceTests/testShellRangeReadsLazyRemoteMountBeforePythonFullRead",
            "mixed workspace host/virtual consistency plus Python subprocess remote/lazy range-read seed",
            "workspace-ui-snapshot-consistency-tests",
            "MSPPlaygroundWorkspaceProfileTests",
            "photosorter-overlay-view-consistency-tests",
            "PhotoLibraryWorkspaceFileSystemPathTests/testPhotoLibraryWorkspaceOverlayKeepsTreeLookupReadPreviewAndRestoreConsistent",
            "photosorter-ui-preview-cache-consistency-tests",
            "MSPPlaygroundViewModelTests/testWorkspaceMediaPreviewInvalidatesCachedContentWhenWorkspaceCacheVersionChanges",
            "PhotoSorter UI preview cache invalidates when the workspace view version changes",
            "photosorter-ui-thumbnail-cache-consistency-tests",
            "MSPPlaygroundShellRuntimePreviewTests/testThumbnailCacheKeyIncludesWorkspaceCacheVersion",
            "PhotoSorter UI thumbnail cache keys include the workspace view version",
            "run_debian12_oracle_conformance.sh",
            "MSP_DEBIAN12_ORACLE_SCRATCH_ROOT=\"$(swiftpm_scratch_path debian12-noninteractive-oracle)\"",
            "DEBIAN12_NONINTERACTIVE_ORACLE_SOURCE_REPORT",
            "DEBIAN12_NONINTERACTIVE_ORACLE_REPORT=\"$OUT_DIR/debian12-noninteractive-oracle-report.json\"",
            "rm -f \"$DEBIAN12_NONINTERACTIVE_ORACLE_SOURCE_REPORT\"",
            "cp \"$DEBIAN12_NONINTERACTIVE_ORACLE_SOURCE_REPORT\" \"$DEBIAN12_NONINTERACTIVE_ORACLE_REPORT\"",
            "run_live_noninteractive_linux_vps_oracle.py",
            "verify_live_noninteractive_linux_vps_oracle_report.py",
            "LIVE_NONINTERACTIVE_LINUX_VPS_ORACLE_REPORT=\"$OUT_DIR/live-noninteractive-linux-vps-oracle-report.json\"",
            "live-noninteractive-linux-vps-oracle",
            "--report \"$LIVE_NONINTERACTIVE_LINUX_VPS_ORACLE_REPORT\"",
            "MSP_DEBIAN12_PTY_ORACLE_BACKEND=linux-external",
            "MSP_DEBIAN12_PTY_ORACLE_REQUIRE_LINUX=1",
            "DEBIAN12_LINUX_PTY_ORACLE_SOURCE_REPORT",
            "DEBIAN12_LINUX_PTY_ORACLE_REPORT=\"$OUT_DIR/debian12-linux-pty-oracle-report.json\"",
            "rm -f \"$DEBIAN12_LINUX_PTY_ORACLE_SOURCE_REPORT\"",
            "cp \"$DEBIAN12_LINUX_PTY_ORACLE_SOURCE_REPORT\" \"$DEBIAN12_LINUX_PTY_ORACLE_REPORT\"",
            "ModelShellProxyDebian12PTYOracleConformanceTests/testMSPV1Debian12PTYOracleConformanceRunner",
            "--scratch-path \"$(swiftpm_scratch_path debian12-linux-pty-oracle)\"",
            "--report \"$DEBIAN12_LINUX_PTY_ORACLE_REPORT\"",
            "--require-linux-runner",
            "--require-all-fixture-cases",
            "--require-python-pty-cases",
            "--expected-case-count 157",
            "MSP_REAL_MODEL_PRESSURE_MATRIX_OUT_DIR=\"$OUT_DIR/real-model-pressure-matrix\"",
            "MSP_REAL_MODEL_PRESSURE_MATRIX_SUITES=host-backed,exec-session,mixed-backend,photosorter-virtual,photosorter-exec-session",
            "MSP_PLAYGROUND_PRESSURE_REQUIRE_PYTHON=1",
            "MSP_PLAYGROUND_PRESSURE_RUN_SHELL_DIAGNOSTIC=1",
            "MSP_PLAYGROUND_RUN_LIFECYCLE_DIAGNOSTIC=1",
            "MSP_PLAYGROUND_PRESSURE_RUN_PYTHON_ORACLE=1",
            "MSP_PLAYGROUND_PRESSURE_RESET_APP=1",
            "MSP_PHOTOSORTER_PRESSURE_REQUIRE_CPYTHON=1",
            "MSP_PHOTOSORTER_PRESSURE_RESET_APP=1",
            "Conformance/Scripts/run_real_model_pressure_matrix.sh",
            "final-exec-session-gate-report.json",
            "\"completion_scope\": \"exec-session-release-gate\"",
            "\"not_final_msp_open_source_release_gate\": True",
            "\"missing_final_gate_classes\": [",
            "remote-backed-workspace-conformance",
            "lazy-materialized-workspace-conformance",
            "full-ui-preview-thumbnail-cache-e2e-conformance",
            "readex-migration-compatibility-conformance",
            "\"model\": model",
            "\"model_matches_required\": model == required_model",
            "\"model_failures\": [] if model == required_model else",
            "\"repository_root\": str(root_dir)",
            "\"out_dir\": str(out_dir)",
            "step_logs",
            "required_pressure_suites",
            "evidence_artifacts",
            "real_model_pressure_preflight_report",
            "real-model-pressure-preflight-report.json",
            "real-model-pressure-preflight-hardening",
            "readex_boundary_report",
            "readex-boundary-report.json",
            "exec_session_stress_report",
            "run_open_source_release_dry_run.py",
            "open-source-release-dry-run",
            "--out-dir \"$OUT_DIR/open-source-release-dry-run\"",
            "--report \"$OUT_DIR/open-source-release-dry-run/open-source-release-dry-run-report.json\"",
            "open_source_release_dry_run_report",
            "open-source-release-dry-run-report.json",
            "run_dynamic_embedded_cpython_swift_tests.sh",
            "dynamic-embedded-cpython-swift-tests",
            "MSP_DYNAMIC_EMBEDDED_CPYTHON_SWIFT_TESTS_OUT_DIR=\"$OUT_DIR/dynamic-embedded-cpython-swift-tests\"",
            "MSP_DYNAMIC_EMBEDDED_CPYTHON_SWIFT_TESTS_SCRATCH_ROOT=\"$OUT_DIR/dynamic-embedded-cpython-swift-tests/scratch\"",
            "dynamic_embedded_cpython_swift_tests_report",
            "dynamic-embedded-cpython-swift-tests-report.json",
            "write_focused_test_suites_ledger.py",
            "focused-test-suites-ledger",
            "--report \"$OUT_DIR/focused-test-suites-ledger/focused-test-suites-ledger-report.json\"",
            "focused_test_suites_ledger_report",
            "focused-test-suites-ledger-report.json",
            "run_full_swift_test_suite.sh",
            "full-swift-test-suite",
            "MSP_FULL_SWIFT_TEST_SUITE_OUT_DIR=\"$OUT_DIR/full-swift-test-suite\"",
            "MSP_FULL_SWIFT_TEST_SUITE_SCRATCH_ROOT=\"$OUT_DIR/full-swift-test-suite/scratch\"",
            "full_swift_test_suite_report",
            "full-swift-test-suite-report.json",
            "run_full_agentbridge_parity_matrix.sh",
            "full-agentbridge-parity-matrix",
            "MSP_FULL_AGENTBRIDGE_PARITY_MATRIX_OUT_DIR=\"$OUT_DIR/full-agentbridge-parity-matrix\"",
            "MSP_FULL_AGENTBRIDGE_PARITY_MATRIX_SCRATCH_ROOT=\"$OUT_DIR/full-agentbridge-parity-matrix/scratch\"",
            "full_agentbridge_parity_matrix_report",
            "full-agentbridge-parity-matrix-report.json",
            "core100_noninteractive_oracle_report",
            "core100-noninteractive-oracle-report.json",
            "debian12_noninteractive_oracle_report",
            "debian12-noninteractive-oracle-report.json",
            "live_noninteractive_linux_vps_oracle_report",
            "live-noninteractive-linux-vps-oracle-report.json",
            "debian12_linux_pty_oracle_report",
            "debian12-linux-pty-oracle-report.json",
            "real_model_pressure_matrix_report",
            "real_model_pressure_suite_reports",
            "pressure-report.json",
            "final gate passed but required evidence artifacts are missing",
            "verify_linux_character_oracle_alignment",
            "alignment_failures",
            "final gate refused to write passed report because Linux character oracle alignment is not clean",
            "verify_final_exec_session_release_gate_report.py",
            "final-exec-session-gate-report-verification.json",
            "final-exec-session-gate-report-verify.log"
        ] {
            XCTAssertTrue(finalGate.contains(required), "final release gate missing \(required)")
        }
        for forbidden in [
            #"str(root_dir / ".build/msp-conformance/debian12-noninteractive-report.json")"#,
            #"str(root_dir / ".build/msp-conformance/debian12-pty-linux-report.json")"#,
            #""open-source-examples-full-build-test""#,
            #"find "$ROOT_DIR" -name .DS_Store -type f -delete"#,
            #"find "$ROOT_DIR" -name __pycache__ -type d -prune -exec rm -rf {} +"#,
            #"find "$ROOT_DIR" -name '*.pyc' -type f -delete"#,
            #"rm -rf "$ROOT_DIR/Implementations/Swift/Sources/Tools/Vendor/Codex/apply_patch/Artifacts/Build""#,
            #"""
            "missing_final_gate_classes": [
                "full-agentbridge-parity-matrix",
            ]
            """#,
            #""missing_final_gate_classes": []"#
        ] {
            XCTAssertFalse(finalGate.contains(forbidden), "final release gate contains forbidden final-report marker: \(forbidden)")
        }

    }
}
