from __future__ import annotations

from typing import Any, Callable

CaseAdder = Callable[[str, list[tuple[str, str, dict[str, Any] | None]]], None]
FileItemFactory = Callable[[str, bytes | str, str], dict[str, Any]]

def add_data_text_cases(add: CaseAdder, add_required: CaseAdder, file_item: FileItemFactory, shell_file: dict[str, Any], source_file: dict[str, Any]) -> None:
    add("dd", [
        ("stdin-stdout", "printf abcdef | dd bs=2 count=2 status=none", {"commands": ["dd", "printf"]}),
        ("file-copy", "printf abcdef > in.bin; dd if=in.bin of=out.bin bs=2 count=2 status=none; cat out.bin", {"commands": ["dd", "printf", "cat"]}),
        ("skip", "printf abcdef > in.bin; dd if=in.bin bs=1 skip=2 count=3 status=none", {"commands": ["dd", "printf"]}),
        ("seek", "printf abcdef > in.bin; dd if=in.bin of=out.bin bs=1 count=2 seek=3 status=none; stat -c '%s' out.bin; od -An -tx1 out.bin", {"commands": ["dd", "printf", "stat", "od"]}),
        ("conv-notrunc", "printf 123456 > out.bin; printf ab > in.bin; dd if=in.bin of=out.bin bs=1 seek=2 conv=notrunc status=none; cat out.bin", {"commands": ["dd", "printf", "cat"]}),
        ("count-zero", "printf abc > in.bin; dd if=in.bin bs=1 count=0 status=none | wc -c", {"commands": ["dd", "printf", "wc"]}),
        ("ibs-obs", "printf abcdef > in.bin; dd if=in.bin ibs=2 obs=3 status=none", {"commands": ["dd", "printf"]}),
        ("fullblock", "printf abcdef > in.bin; dd if=in.bin bs=4 count=2 iflag=fullblock status=none", {"commands": ["dd", "printf"]}),
        ("missing-if", "dd if=missing of=out status=none; printf 'status:%s\\n' \"$?\"", {"commands": ["dd", "printf"]}),
        ("invalid-bs", "dd bs=nope count=1 status=none; printf 'status:%s\\n' \"$?\"", {"commands": ["dd", "printf"]}),
        ("status-none", "printf abc | dd bs=1 count=2 status=none", {"commands": ["dd", "printf"]}),
        ("status-noxfer", "printf abc | dd bs=1 count=2 status=noxfer", {"commands": ["dd", "printf"]}),
        ("append", "printf old > out; printf new | dd of=out oflag=append conv=notrunc status=none; cat out", {"commands": ["dd", "printf", "cat"]}),
        ("swab", "printf abcd | dd conv=swab status=none", {"commands": ["dd", "printf"]}),
        ("sync", "printf ab | dd bs=4 conv=sync status=none | od -An -tx1", {"commands": ["dd", "printf", "od"]}),
        ("no-operands", "printf abc | dd status=none", {"commands": ["dd", "printf"]}),
        ("two-files", "printf alpha > a; printf beta > b; dd if=a of=out bs=10 status=none; dd if=b of=out2 bs=10 status=none; cat out out2", {"commands": ["dd", "printf", "cat"]}),
        ("large-bounded", "python3 - <<'PY'\nopen('in.bin','wb').write(b'a'*4096)\nPY\ndd if=in.bin of=out.bin bs=512 count=3 status=none; stat -c '%s' out.bin", {"commands": ["dd", "python3", "stat"]}),
        ("stderr-default", "printf abc | dd bs=1 count=2 >dd-out.txt 2>err.txt; cat err.txt | head -n 2", {"commands": ["dd", "printf", "cat", "head"]}),
        ("space-path", "printf abc > 'in file'; dd 'if=in file' 'of=out file' bs=1 count=2 status=none; cat 'out file'", {"commands": ["dd", "printf", "cat"]}),
    ])

    add("split", [
        ("default", "printf 'a\\nb\\nc\\n' > in.txt; split in.txt; find . -maxdepth 1 -type f -name 'x*' -printf '%f:%s\\n' | sort", {"commands": ["split", "printf", "find", "sort"]}),
        ("lines", "printf '1\\n2\\n3\\n4\\n' | split -l 2 - part-; find . -maxdepth 1 -name 'part-*' -printf '%f:%s\\n' | sort", {"commands": ["split", "printf", "find", "sort"]}),
        ("bytes", "printf abcdef | split -b 2 - chunk-; find . -maxdepth 1 -name 'chunk-*' -printf '%f:%s\\n' | sort", {"commands": ["split", "printf", "find", "sort"]}),
        ("numeric", "printf abcdef | split -b 2 -d - chunk-; find . -maxdepth 1 -name 'chunk-*' -printf '%f\\n' | sort", {"commands": ["split", "printf", "find", "sort"]}),
        ("suffix", "printf abcdef | split -b 2 --additional-suffix=.txt - chunk-; find . -maxdepth 1 -name 'chunk-*' -printf '%f\\n' | sort", {"commands": ["split", "printf", "find", "sort"]}),
        ("number-chunks", "printf abcdef | split -n 3 - chunk-; find . -maxdepth 1 -name 'chunk-*' -printf '%f:%s\\n' | sort", {"commands": ["split", "printf", "find", "sort"]}),
        ("filter-deferred-safe", "printf abc | split -b 1 - out-; cat out-*", {"commands": ["split", "printf", "cat"]}),
        ("missing-input", "split missing out-; printf 'status:%s\\n' \"$?\"", {"commands": ["split", "printf"]}),
        ("invalid-size", "printf abc | split -b nope - out-; printf 'status:%s\\n' \"$?\"", {"commands": ["split", "printf"]}),
        ("line-bytes-conflict", "printf abc | split -b 1 -l 1 - out-; printf 'status:%s\\n' \"$?\"", {"commands": ["split", "printf"]}),
        ("stdin-default", "printf 'a\\nb\\n' | split; find . -maxdepth 1 -name 'x*' -printf '%f:%s\\n' | sort", {"commands": ["split", "printf", "find", "sort"]}),
        ("long-lines", "python3 - <<'PY' > in.txt\nprint('x'*200)\nprint('y'*200)\nPY\nsplit -l 1 in.txt long-; find . -maxdepth 1 -name 'long-*' -printf '%f:%s\\n' | sort", {"commands": ["split", "python3", "find", "sort"]}),
        ("elide-empty", "printf abc | split -n r/3 - out-; find . -maxdepth 1 -name 'out-*' -printf '%f:%s\\n' | sort", {"commands": ["split", "printf", "find", "sort"]}),
        ("hex-suffix", "printf abcdef | split -b 2 -x - out-; find . -maxdepth 1 -name 'out-*' -printf '%f\\n' | sort", {"commands": ["split", "printf", "find", "sort"]}),
        ("suffix-length", "printf abcdef | split -b 2 -a 3 - out-; find . -maxdepth 1 -name 'out-*' -printf '%f\\n' | sort", {"commands": ["split", "printf", "find", "sort"]}),
        ("separator", "printf abcdef | split -b 2 --separator='|' - out-; find . -maxdepth 1 -name 'out-*' -printf '%f:%s\\n' | sort", {"commands": ["split", "printf", "find", "sort"]}),
        ("verbose", "printf abc | split -b 1 --verbose - out-", {"commands": ["split", "printf"]}),
        ("space-prefix", "printf abc | split -b 1 - 'out file-'; find . -maxdepth 1 -name 'out file-*' -printf '%f\\n' | sort", {"commands": ["split", "printf", "find", "sort"]}),
    ])

    add("install", [
        ("copy", "printf abc > src; install src dst; stat -c '%a %s' dst; cat dst", {"commands": ["install", "printf", "stat", "cat"]}),
        ("mode", "printf abc > src; install -m 755 src dst; stat -c '%a' dst", {"commands": ["install", "printf", "stat"]}),
        ("directory", "install -d -m 700 a/b; stat -c '%a %F' a a/b", {"commands": ["install", "stat"]}),
        ("capital-d", "printf abc > src; install -D src bin/tool; find . -maxdepth 3 -printf '%p|%m|%s\\n' | sort", {"commands": ["install", "printf", "find", "sort"]}),
        ("capital-t", "printf abc > src; mkdir dst; install -T src dst; printf 'status:%s\\n' \"$?\"", {"commands": ["install", "printf", "mkdir"]}),
        ("backup", "printf one > src; printf old > dst; install -b src dst; find . -maxdepth 1 -type f -printf '%f:%s\\n' | sort", {"commands": ["install", "printf", "find", "sort"]}),
        ("compare", "printf abc > src; printf abc > dst; install -C src dst; stat -c '%s' dst", {"commands": ["install", "printf", "stat"]}),
        ("strip-safe-error", "printf abc > src; install -s src dst; printf 'status:%s\\n' \"$?\"", {"commands": ["install", "printf"]}),
        ("missing-source", "install missing dst; printf 'status:%s\\n' \"$?\"", {"commands": ["install", "printf"]}),
        ("no-operand", "install; printf 'status:%s\\n' \"$?\"", {"commands": ["install", "printf"]}),
        ("multiple-to-dir", "mkdir dir; printf a > a; printf b > b; install a b dir; find dir -type f -printf '%f:%s\\n' | sort", {"commands": ["install", "mkdir", "printf", "find", "sort"]}),
        ("target-dir-option", "mkdir dir; printf a > a; install -t dir a; find dir -type f -printf '%f:%s\\n'", {"commands": ["install", "mkdir", "printf", "find"]}),
        ("preserve-timestamps", "printf a > a; install -p a b; stat -c '%s' b", {"commands": ["install", "printf", "stat"]}),
        ("invalid-mode", "printf a > a; install -m nope a b; printf 'status:%s\\n' \"$?\"", {"commands": ["install", "printf"]}),
        ("space-path", "printf a > 'a b'; install 'a b' 'c d'; cat 'c d'", {"commands": ["install", "printf", "cat"]}),
        ("owner-deferred", "printf a > a; install -o nobody a b; printf 'status:%s\\n' \"$?\"", {"commands": ["install", "printf"]}),
        ("group-deferred", "printf a > a; install -g nogroup a b; printf 'status:%s\\n' \"$?\"", {"commands": ["install", "printf"]}),
        ("verbose", "printf a > a; install -v a b", {"commands": ["install", "printf"]}),
    ])

    add("tree", [
        ("presence", "command -v tree; printf 'status:%s\\n' \"$?\"", {"commands": ["tree", "command", "printf"]}),
        ("default", "mkdir -p a/b; : > a/file.txt; tree", {"commands": ["tree", "mkdir", ":"]}),
        ("all", "mkdir -p a; : > a/.hidden; tree -a", {"commands": ["tree", "mkdir", ":"]}),
        ("depth", "mkdir -p a/b/c; : > a/b/file; tree -L 2", {"commands": ["tree", "mkdir", ":"]}),
        ("dirs-only", "mkdir -p a/b; : > a/file; tree -d", {"commands": ["tree", "mkdir", ":"]}),
        ("full-path", "mkdir -p a; : > a/file; tree -f", {"commands": ["tree", "mkdir", ":"]}),
        ("no-indent", "mkdir -p a; : > a/file; tree -i", {"commands": ["tree", "mkdir", ":"]}),
        ("empty", "tree", {"commands": ["tree"]}),
        ("charset", "mkdir -p a; : > a/file; tree --charset ascii", {"commands": ["tree", "mkdir", ":"]}),
        ("pattern", "mkdir -p a; : > a/one.txt; : > a/two.md; tree -P '*.txt'", {"commands": ["tree", "mkdir", ":"]}),
        ("ignore", "mkdir -p a; : > a/one.txt; : > a/two.md; tree -I '*.md'", {"commands": ["tree", "mkdir", ":"]}),
        ("space", "mkdir -p 'space dir'; : > 'space dir/file'; tree", {"commands": ["tree", "mkdir", ":"]}),
        ("symlink", "mkdir a; : > a/file; ln -s a link; tree", {"commands": ["tree", "mkdir", "ln", ":"]}),
        ("invalid-option", "tree -Z; printf 'status:%s\\n' \"$?\"", {"commands": ["tree", "printf"]}),
    ])

    add("expr", [
        ("add", "expr 1 + 2", None),
        ("multiply", "expr 2 \\* 3", None),
        ("compare-true", "expr 5 \\> 3; printf 'status:%s\\n' \"$?\"", {"commands": ["expr", "printf"]}),
        ("compare-false", "expr 1 \\> 3; printf 'status:%s\\n' \"$?\"", {"commands": ["expr", "printf"]}),
        ("string-length", "expr length abc", None),
        ("substr", "expr substr abcdef 2 3", None),
        ("index", "expr index abcdef de", None),
        ("regex", "expr abc123 : 'abc\\([0-9]*\\)'", None),
        ("match-false", "expr abc : 'z'; printf 'status:%s\\n' \"$?\"", {"commands": ["expr", "printf"]}),
        ("syntax", "expr 1 +; printf 'status:%s\\n' \"$?\"", {"commands": ["expr", "printf"]}),
        ("division", "expr 7 / 2", None),
        ("modulo", "expr 7 % 2", None),
        ("or", "expr '' '|' fallback", None),
        ("and", "expr value '&' other", None),
        ("paren", "expr \\( 1 + 2 \\) \\* 3", None),
        ("negative", "expr -1 + 2", None),
    ])

    add("strings", [
        ("default", "python3 - <<'PY'\nopen('bin.dat','wb').write(b'\\0abcde\\0xy\\0longer-string\\0')\nPY\nstrings bin.dat", {"commands": ["strings", "python3"]}),
        ("min", "python3 - <<'PY'\nopen('bin.dat','wb').write(b'abc\\0abcdef\\0')\nPY\nstrings -n 5 bin.dat", {"commands": ["strings", "python3"]}),
        ("all", "python3 - <<'PY'\nopen('bin.dat','wb').write(b'abcde\\0')\nPY\nstrings -a bin.dat", {"commands": ["strings", "python3"]}),
        ("offset-decimal", "python3 - <<'PY'\nopen('bin.dat','wb').write(b'\\0\\0abcd\\0')\nPY\nstrings -t d bin.dat", {"commands": ["strings", "python3"]}),
        ("offset-hex", "python3 - <<'PY'\nopen('bin.dat','wb').write(b'\\0\\0abcd\\0')\nPY\nstrings -t x bin.dat", {"commands": ["strings", "python3"]}),
        ("stdin", "printf '\\0hello\\0' | strings", {"commands": ["strings", "printf"]}),
        ("no-strings", "python3 - <<'PY'\nopen('bin.dat','wb').write(bytes(range(4)))\nPY\nstrings bin.dat; printf 'status:%s\\n' \"$?\"", {"commands": ["strings", "python3", "printf"]}),
        ("missing", "strings missing; printf 'status:%s\\n' \"$?\"", {"commands": ["strings", "printf"]}),
        ("invalid-option", "strings -Z bin.dat; printf 'status:%s\\n' \"$?\"", {"commands": ["strings", "printf"]}),
        ("encoding", "python3 - <<'PY'\nopen('bin.dat','wb').write('hello'.encode('utf-16le'))\nPY\nstrings -e l bin.dat", {"commands": ["strings", "python3"]}),
        ("space-path", "python3 - <<'PY'\nopen('a b','wb').write(b'hello\\0')\nPY\nstrings 'a b'", {"commands": ["strings", "python3"]}),
        ("version", "strings --version | head -n 1", {"commands": ["strings", "head"]}),
    ])

    add("fold", [
        ("default", "printf 'abcdefghij\\n' | fold", {"commands": ["fold", "printf"]}),
        ("width", "printf 'abcdef\\n' | fold -w 3", {"commands": ["fold", "printf"]}),
        ("spaces", "printf 'aa bb cc\\n' | fold -s -w 5", {"commands": ["fold", "printf"]}),
        ("bytes", "printf 'ééé\\n' | fold -b -w 3", {"commands": ["fold", "printf"]}),
        ("file", "printf 'abcdef\\n' > in.txt; fold -w 2 in.txt", {"commands": ["fold", "printf"]}),
        ("multiple-files", "printf abc > a; printf def > b; fold -w 2 a b", {"commands": ["fold", "printf"]}),
        ("invalid-width", "fold -w nope; printf 'status:%s\\n' \"$?\"", {"commands": ["fold", "printf"]}),
        ("missing-file", "fold missing; printf 'status:%s\\n' \"$?\"", {"commands": ["fold", "printf"]}),
        ("long-line", "python3 - <<'PY' | fold -w 50\nprint('x'*160)\nPY", {"commands": ["fold", "python3"]}),
        ("space-path", "printf abcdef > 'a b'; fold -w 3 'a b'", {"commands": ["fold", "printf"]}),
        ("old-width", "printf 'abcdef\\n' | fold -3", {"commands": ["fold", "printf"]}),
        ("carriage-return", "printf 'ab\\rcdef\\n' | fold -w 4 | od -An -tx1", {"commands": ["fold", "printf", "od"]}),
        ("backspace", "python3 - <<'PY' | fold -w 3 | od -An -tx1\nimport sys\nsys.stdout.buffer.write(bytes([0x61,0x62,0x08,0x63,0x64,0x0a]))\nPY", {"commands": ["fold", "python3", "od"]}),
    ])

    add("expand", [
        ("default", "printf 'a\\tb\\n' | expand", {"commands": ["expand", "printf"]}),
        ("tabs", "printf 'a\\tb\\tc\\n' | expand -t 4", {"commands": ["expand", "printf"]}),
        ("tab-list", "printf 'a\\tb\\tc\\n' | expand -t 2,6", {"commands": ["expand", "printf"]}),
        ("initial", "printf '\\ta\\tb\\n' | expand -i -t 4", {"commands": ["expand", "printf"]}),
        ("file", "printf 'a\\tb\\n' > in.txt; expand in.txt", {"commands": ["expand", "printf"]}),
        ("multiple", "printf 'a\\tb\\n' > a; printf 'c\\td\\n' > b; expand -t 4 a b", {"commands": ["expand", "printf"]}),
        ("invalid", "expand -t nope; printf 'status:%s\\n' \"$?\"", {"commands": ["expand", "printf"]}),
        ("missing", "expand missing; printf 'status:%s\\n' \"$?\"", {"commands": ["expand", "printf"]}),
        ("space-path", "printf 'a\\tb\\n' > 'a b'; expand 'a b'", {"commands": ["expand", "printf"]}),
        ("no-tabs", "printf 'abc\\n' | expand", {"commands": ["expand", "printf"]}),
        ("obsolete-width", "printf 'a\\tb\\n' | expand -4", {"commands": ["expand", "printf"]}),
        ("repeat-tabstop", "printf 'a\\tb\\tc\\n' | expand -t 2,+4", {"commands": ["expand", "printf"]}),
        ("extend-tabstop", "printf 'a\\tb\\tc\\n' | expand -t 2,/4", {"commands": ["expand", "printf"]}),
        ("initial-carriage-return", "printf 'ab\\rc\\td\\n' | expand -t 4 | od -An -tx1", {"commands": ["expand", "printf", "od"]}),
        ("invalid-byte", "python3 - <<'PY' | expand -t 4 | od -An -tx1\nimport sys\nsys.stdout.buffer.write(bytes([0xff,0x09,0x41,0x0a]))\nPY", {"commands": ["expand", "python3", "od"]}),
    ])

    add("unexpand", [
        ("default", "printf '        x\\n' | unexpand", {"commands": ["unexpand", "printf"]}),
        ("all", "printf 'a       b\\n' | unexpand -a", {"commands": ["unexpand", "printf"]}),
        ("tabs", "printf '    x\\n' | unexpand -t 4", {"commands": ["unexpand", "printf"]}),
        ("tab-list", "printf '  a   b\\n' | unexpand -a -t 2,6", {"commands": ["unexpand", "printf"]}),
        ("file", "printf '        x\\n' > in.txt; unexpand in.txt", {"commands": ["unexpand", "printf"]}),
        ("multiple", "printf '        x\\n' > a; printf '        y\\n' > b; unexpand a b", {"commands": ["unexpand", "printf"]}),
        ("invalid", "unexpand -t nope; printf 'status:%s\\n' \"$?\"", {"commands": ["unexpand", "printf"]}),
        ("missing", "unexpand missing; printf 'status:%s\\n' \"$?\"", {"commands": ["unexpand", "printf"]}),
        ("space-path", "printf '        x\\n' > 'a b'; unexpand 'a b'", {"commands": ["unexpand", "printf"]}),
        ("no-spaces", "printf 'abc\\n' | unexpand", {"commands": ["unexpand", "printf"]}),
        ("first-only", "printf '    a    b\\n' | unexpand -t 4 --first-only | od -An -tx1", {"commands": ["unexpand", "printf", "od"]}),
        ("obsolete-width", "printf '    x\\n' | unexpand -4 | od -An -tx1", {"commands": ["unexpand", "printf", "od"]}),
        ("repeat-tabstop", "printf '  a   b\\n' | unexpand -a -t 2,+4 | od -An -tx1", {"commands": ["unexpand", "printf", "od"]}),
        ("carriage-return", "printf 'ab\\rc   d\\n' | unexpand -a -t 4 | od -An -tx1", {"commands": ["unexpand", "printf", "od"]}),
        ("invalid-byte", "python3 - <<'PY' | unexpand -a -t 4 | od -An -tx1\nimport sys\nsys.stdout.buffer.write(bytes([0xff,0x20,0x20,0x20,0x41,0x0a]))\nPY", {"commands": ["unexpand", "python3", "od"]}),
    ])

    add("fmt", [
        ("default", "printf 'alpha beta gamma delta epsilon zeta eta theta\\n' | fmt", {"commands": ["fmt", "printf"]}),
        ("width", "printf 'alpha beta gamma delta\\n' | fmt -w 12", {"commands": ["fmt", "printf"]}),
        ("split-only", "printf 'alpha beta gamma delta\\n' | fmt -s -w 12", {"commands": ["fmt", "printf"]}),
        ("tagged-goal", "printf 'Tag: alpha beta gamma delta epsilon\\n' | fmt -t -g 18 -w 24", {"commands": ["fmt", "printf"]}),
        ("old-width", "printf 'alpha beta gamma delta\\n' | fmt -10", {"commands": ["fmt", "printf"]}),
        ("uniform", "printf 'alpha.  beta?   gamma!\\n' | fmt -u", {"commands": ["fmt", "printf"]}),
        ("paragraphs", "printf 'a b c d\\n\\ne f g h\\n' | fmt -w 5", {"commands": ["fmt", "printf"]}),
        ("file", "printf 'alpha beta gamma delta\\n' > in.txt; fmt -w 12 in.txt", {"commands": ["fmt", "printf"]}),
        ("multiple", "printf 'a b c\\n' > a; printf 'd e f\\n' > b; fmt -w 5 a b", {"commands": ["fmt", "printf"]}),
        ("prefix", "printf '# alpha beta gamma\\n# delta epsilon\\n' | fmt -p '# ' -w 12", {"commands": ["fmt", "printf"]}),
        ("crown", "printf '> alpha beta\\n> gamma delta\\n' | fmt -c -w 12", {"commands": ["fmt", "printf"]}),
        ("invalid-width", "fmt -w nope; printf 'status:%s\\n' \"$?\"", {"commands": ["fmt", "printf"]}),
        ("missing", "fmt missing; printf 'status:%s\\n' \"$?\"", {"commands": ["fmt", "printf"]}),
        ("space-path", "printf 'alpha beta gamma\\n' > 'a b'; fmt -w 8 'a b'", {"commands": ["fmt", "printf"]}),
        ("mail-quote-prefix", "printf '> alpha beta gamma\\n> delta epsilon zeta\\n' | fmt -p '> ' -w 16", {"commands": ["fmt", "printf"]}),
        ("tagged-single-line-fallback", "printf 'alpha beta gamma delta epsilon\\n\\none two three four five\\n' | fmt -t -w 14", {"commands": ["fmt", "printf"]}),
        ("crown-indented-follow", "printf 'Title alpha beta\\n  follow gamma delta epsilon\\n  more zeta eta\\n' | fmt -c -w 18", {"commands": ["fmt", "printf"]}),
        ("split-preserves-line-boundaries", "printf 'alpha beta gamma\\ndelta epsilon zeta\\n' | fmt -s -w 12", {"commands": ["fmt", "printf"]}),
        ("goal-narrow", "printf 'alpha beta gamma delta epsilon\\n' | fmt -g 12 -w 20", {"commands": ["fmt", "printf"]}),
        ("goal-too-wide", "fmt -g 90 -w 80; printf 'status:%s\\n' \"$?\"", {"commands": ["fmt", "printf"]}),
        ("old-width-not-first", "fmt -w 20 -10; printf 'status:%s\\n' \"$?\"", {"commands": ["fmt", "printf"]}),
        ("multi-file-missing-present", "printf 'alpha beta gamma\\n' > ok.txt; fmt -w 8 missing ok.txt; printf 'status:%s\\n' \"$?\"", {"commands": ["fmt", "printf"]}),
        ("long-word", "printf 'supercalifragilisticexpialidocious tiny words\\n' | fmt -w 10", {"commands": ["fmt", "printf"]}),
        ("invalid-byte", "python3 - <<'PY' | fmt -w 10 | od -An -tx1\nimport sys\nsys.stdout.buffer.write(bytes([0xff,0x20,0x61,0x6c,0x70,0x68,0x61,0x20,0x62,0x65,0x74,0x61,0x0a]))\nPY", {"commands": ["fmt", "python3", "od"]}),
        ("huge-paragraph-line-count", "python3 - <<'PY' | fmt -w 50 | wc -l\nprint(' '.join(['word'] * 1200))\nPY", {"commands": ["fmt", "python3", "wc"], "timeout_seconds": 10.0}),
    ])
