from __future__ import annotations

from typing import Any, Callable

CaseFactory = Callable[..., dict[str, Any]]


def add_stress_cases(cases: list[dict[str, Any]], case: CaseFactory) -> None:
    stress = [
        ("stress-s0-pipeline-basic", "printf 'alpha\\nbeta\\n' | grep a | sed 's/a/A/g' | awk '{print NR\":\"$0}' | wc -c", ["printf", "grep", "sed", "awk", "wc"], "sh"),
        ("stress-s0-pipeline-failure-status", "set -o pipefail; false | true; printf 'status:%s pipe:%s\\n' \"$?\" \"${PIPESTATUS[*]}\"", ["set", "false", "true", "printf"], "bash"),
        ("stress-s0-redirection-basic", "printf out > a.txt; printf err >&2 2>err.txt; cat a.txt; cat err.txt", ["printf", "cat"], "sh"),
        ("stress-s0-sequential-and-or", "false || printf alt; true && printf ok; ! false; printf ':%s\\n' \"$?\"", ["false", "true", "printf"], "sh"),
        ("stress-s0-subshell-cwd", "mkdir d; (cd d; pwd); pwd", ["mkdir", "cd", "pwd"], "sh"),
        ("stress-s0-group-redirection", "{ printf a; printf b; } > out.txt; cat out.txt", ["printf", "cat"], "sh"),
        ("stress-s0-command-substitution", "printf '<%s>\\n' \"$(printf 'a\\nb\\n')\"", ["printf"], "sh"),
        ("stress-s0-quoted-words", "printf '<%s>\\n' '' 'two words' \"three words\" a\\ b", ["printf"], "sh"),
        ("stress-s0-glob-basic", "touch a.txt b.md; printf '%s\\n' *.txt", ["touch", "printf"], "bash"),
        ("stress-s0-heredoc-basic", "cat <<'EOF'\nalpha $HOME\nEOF", ["cat"], "sh"),
        ("stress-s0-function-basic", "f(){ printf '%s/%s\\n' \"$1\" \"$2\"; }; f a b", ["printf"], "bash"),
        ("stress-s0-loop-basic", "for x in a b c; do [ \"$x\" = b ] && continue; printf '%s\\n' \"$x\"; done", ["printf", "test"], "sh"),
        ("stress-s1-overlong-command-line", "payload='" + ("abc123XYZ_" * 500) + "'; printf '%s\\n' \"${#payload}\"", ["printf"], "bash"),
        ("stress-s1-overlong-single-argument", "python3 - <<'PY'\nprint(len('" + ("x" * 2000) + "'))\nPY", ["python3"], "bash"),
        ("stress-s1-overlong-env-assignment", "LONG='" + ("env" * 700) + "' env | grep '^LONG=' | wc -c", ["env", "grep", "wc"], "bash"),
        ("stress-s1-overlong-pipeline", "seq 1 30" + " | cat" * 25 + " | tail -n 1", ["seq", "cat", "tail"], "bash"),
        ("stress-s1-many-redirections", "exec 3>three.txt 4>four.txt; printf three >&3; printf four >&4; exec 3>&- 4>&-; cat three.txt four.txt", ["printf", "cat"], "bash"),
        ("stress-s1-nested-command-substitution", "printf '%s\\n' \"$(printf '%s' \"$(printf nested)\")\"", ["printf"], "bash"),
        ("stress-s1-arithmetic-expansion", "a=5; b=7; printf '%s\\n' \"$((a*b+3))\"", ["printf"], "bash"),
        ("stress-s1-parameter-defaults", "unset x; printf '%s/%s/%s\\n' \"${x:-fallback}\" \"${x:=set}\" \"$x\"", ["unset", "printf"], "bash"),
        ("stress-s1-parameter-substrings", "x=abcdef; printf '%s/%s\\n' \"${x:1:3}\" \"${x: -2}\"", ["printf"], "bash"),
        ("stress-s1-parameter-patterns", "x=src/file.test.txt; printf '%s/%s/%s/%s\\n' \"${x#*/}\" \"${x##*.}\" \"${x%.*}\" \"${x//t/T}\"", ["printf"], "bash"),
        ("stress-s1-brace-expansion", "printf '%s\\n' a{1..3}{x,y}", ["printf"], "bash"),
        ("stress-s1-extglob", "shopt -s extglob; touch a.txt b.md c.txt; printf '%s\\n' !(*.md) | sort", ["touch", "printf", "sort"], "bash"),
        ("stress-s1-globstar", "shopt -s globstar; mkdir -p a/b; touch a/b/c.txt; printf '%s\\n' **/*.txt", ["mkdir", "touch", "printf"], "bash"),
        ("stress-s1-nullglob-failglob-dotglob", "touch .hidden; shopt -s dotglob nullglob; printf '%s\\n' * missing*", ["touch", "printf"], "bash"),
        ("stress-s1-heredoc-quoted", "X=value; cat <<'EOF'\n$X\nEOF", ["cat"], "bash"),
        ("stress-s1-heredoc-tabs", "cat <<-EOF\n\talpha\nEOF", ["cat"], "bash"),
        ("stress-s1-here-string", "cat <<< 'alpha beta'", ["cat"], "bash"),
        ("stress-s1-case-patterns", "x=beta; case \"$x\" in a*) echo A;; b*) echo B;; *) echo Z;; esac", ["echo"], "sh"),
        ("stress-s1-if-test-compound", "if [ -n x ] && true; then echo yes; else echo no; fi", ["test", "true", "echo"], "sh"),
        ("stress-s1-functions-local-return", "f(){ local x=inner; return 3; }; x=outer; f; printf '%s/%s\\n' \"$?\" \"$x\"", ["printf"], "bash"),
        ("stress-s1-source-state", "printf 'X=sourced\\n' > s.sh; source s.sh; printf '%s\\n' \"$X\"", ["source", "printf"], "bash"),
        ("stress-s1-eval-reparse", "x='printf eval:%s\\\\n ok'; eval \"$x\"", ["printf"], "bash"),
        ("stress-s1-arrays-indexed", "a=([2]=two [5]=five); printf '%s/%s/%s\\n' \"${a[2]}\" \"${a[5]}\" \"${#a[@]}\"", ["printf"], "bash"),
        ("stress-s1-arrays-associative", "declare -A m=([a]=1 ['b c']=2); printf '%s/%s\\n' \"${m[a]}\" \"${m['b c']}\"", ["declare", "printf"], "bash"),
        ("stress-s1-nameref", "target=value; declare -n ref=target; ref=changed; printf '%s\\n' \"$target\"", ["declare", "printf"], "bash"),
        ("stress-s1-process-substitution-input", "cat <(printf proc)", ["cat", "printf"], "bash"),
        ("stress-s1-process-substitution-output", "tee >(wc -c > count.txt) > stdout.txt <<< abc; cat count.txt stdout.txt", ["tee", "wc", "cat"], "bash"),
        ("stress-s1-binary-stdout", "python3 - <<'PY'\nimport sys\nsys.stdout.buffer.write(bytes([0,1,65,255]))\nPY", ["python3"], "bash"),
        ("stress-s1-binary-stderr", "python3 - <<'PY'\nimport sys\nsys.stderr.buffer.write(bytes([0,2,66,254]))\nPY", ["python3"], "bash"),
        ("stress-s1-non-utf8-stdin", "python3 - <<'PY' | od -An -tx1\nimport sys\nsys.stdout.buffer.write(bytes([0xff,0xfe,65]))\nPY", ["python3", "od"], "bash"),
        ("stress-s2-large-file-stream-head", "python3 - <<'PY' > big.txt\nfor i in range(5000): print('line', i)\nPY\ncat big.txt | head -n 3", ["python3", "cat", "head"], "bash"),
        ("stress-s2-large-directory-find-head", "python3 - <<'PY'\nimport os\nos.makedirs('tree', exist_ok=True)\nfor i in range(500): open(f'tree/f{i}.txt','w').write('x')\nPY\nfind tree -type f | head -n 5", ["python3", "find", "head"], "bash"),
        ("stress-s2-large-directory-ls-head", "python3 - <<'PY'\nimport os\nos.makedirs('tree', exist_ok=True)\nfor i in range(500): open(f'tree/f{i}.txt','w').write('x')\nPY\nls -U tree | head -n 5", ["python3", "ls", "head"], "bash"),
        ("stress-s2-large-grep-quiet", "python3 - <<'PY' > big.txt\nprint('needle')\nfor i in range(5000): print('hay')\nPY\ngrep -q needle big.txt; printf 'status:%s\\n' \"$?\"", ["python3", "grep", "printf"], "bash"),
        ("stress-s2-yes-head-broken-pipe", "yes y | head -n 3", ["yes", "head"], "bash"),
        ("stress-s2-timeout-sleep", "timeout 0.05 sleep 1; printf 'status:%s\\n' \"$?\"", ["timeout", "sleep", "printf"], "bash"),
        ("stress-s2-timeout-noncooperative", "timeout 0.05 sh -c 'while :; do :; done'; printf 'status:%s\\n' \"$?\"", ["timeout", "sh", ":", "printf"], "bash"),
        ("stress-s2-xargs-batching-long-input", "seq 1 50 | xargs -n 13 printf '<%s>\\n' | tail -n 5", ["seq", "xargs", "printf", "tail"], "bash"),
        ("stress-s2-sort-large-input", "seq 200 -1 1 | sort -n | tail -n 3", ["seq", "sort", "tail"], "bash"),
        ("stress-s2-diff-large-early-mismatch", "python3 - <<'PY'\nopen('a','w').write('X\\n'+'a\\n'*1000)\nopen('b','w').write('Y\\n'+'a\\n'*1000)\nPY\ndiff -q a b; printf 'status:%s\\n' \"$?\"", ["python3", "diff", "printf"], "bash"),
        ("stress-s2-cmp-large-early-mismatch", "python3 - <<'PY'\nopen('a','wb').write(b'X'+b'a'*5000)\nopen('b','wb').write(b'Y'+b'a'*5000)\nPY\ncmp a b; printf 'status:%s\\n' \"$?\"", ["python3", "cmp", "printf"], "bash"),
        ("stress-s2-dd-limited-copy", "python3 - <<'PY'\nopen('in','wb').write(b'a'*2048)\nPY\ndd if=in of=out bs=256 count=3 status=none; stat -c '%s' out", ["python3", "dd", "stat"], "bash"),
        ("stress-s2-split-output-fanout", "seq 1 30 | split -l 7 - out-; find . -maxdepth 1 -name 'out-*' -printf '%f:%s\\n' | sort", ["seq", "split", "find", "sort"], "bash"),
        ("stress-s2-shuf-deterministic", "printf '0123456789abcdef' > random.bin; seq 1 10 | shuf --random-source=random.bin -n 5", ["printf", "seq", "shuf"], "bash"),
        ("stress-s2-sleep-cancel", "timeout 0.05 sleep 2; printf 'status:%s\\n' \"$?\"", ["timeout", "sleep", "printf"], "bash"),
    ]
    for case_id, command_line, commands, shell in stress:
        cases.append(case(case_id, command_line, commands, shell=shell, category="core100-shell-stress", timeout_seconds=3.0))
