#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../../.." && pwd)"
signing_dir="$repo_root/Examples/iOS/Shared/Signing"
local_config="$signing_dir/ExampleSigning.local.xcconfig"

usage() {
  cat <<USAGE
Usage:
  $0 --team TEAM_ID --bundle-prefix REVERSE_DNS_PREFIX [--skip-cpython]

Example:
  $0 --team ABCDE12345 --bundle-prefix com.yourname.msp

Writes the ignored local signing config used by the public iOS example projects
and pre-populates the BeeWare CPython iOS cache used by direct Xcode builds.
USAGE
}

team=""
bundle_prefix=""
skip_cpython=0

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --team)
      team="${2:-}"
      shift 2
      ;;
    --bundle-prefix)
      bundle_prefix="${2:-}"
      shift 2
      ;;
    --skip-cpython)
      skip_cpython=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$team" || -z "$bundle_prefix" ]]; then
  usage >&2
  exit 2
fi

mkdir -p "$signing_dir"
cat >"$local_config" <<EOF
// Generated by Examples/iOS/Tools/bootstrap-ios-examples.sh.
// This file is ignored and should stay local to your machine.

MSP_EXAMPLE_DEVELOPMENT_TEAM = $team
MSP_EXAMPLE_BUNDLE_ID_PREFIX = $bundle_prefix
EOF

echo "wrote $local_config"

if [[ "$skip_cpython" != "1" ]]; then
  MSP_CPYTHON_APPLE_SUPPORT_PLATFORMS=iOS \
    "$repo_root/Conformance/Scripts/cache_beeware_cpython_apple_support.sh" >/dev/null
  echo "cached BeeWare CPython iOS support"
fi

cat <<EOF

Next:
  open Examples/iOS/MSPPlaygroundApp/Project/MSPPlaygroundApp.xcodeproj
  open Examples/iOS/PhotoSorter/Project/PhotoSorter.xcodeproj
  select your connected iPhone or iPad in Xcode, then press Run

Or build from the command line:
  xcodebuild -project Examples/iOS/MSPPlaygroundApp/Project/MSPPlaygroundApp.xcodeproj -scheme MSPPlaygroundApp -configuration Debug -sdk iphoneos -destination 'generic/platform=iOS' build
  xcodebuild -project Examples/iOS/PhotoSorter/Project/PhotoSorter.xcodeproj -scheme PhotoSorter -configuration Debug -sdk iphoneos -destination 'generic/platform=iOS' build
EOF
